// Code generated by protoc-gen-go. DO NOT EDIT.
// source: api.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type DeviceSet struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceSet) Reset()         { *m = DeviceSet{} }
func (m *DeviceSet) String() string { return proto.CompactTextString(m) }
func (*DeviceSet) ProtoMessage()    {}
func (*DeviceSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{0}
}

func (m *DeviceSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSet.Unmarshal(m, b)
}
func (m *DeviceSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSet.Marshal(b, m, deterministic)
}
func (m *DeviceSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSet.Merge(m, src)
}
func (m *DeviceSet) XXX_Size() int {
	return xxx_messageInfo_DeviceSet.Size(m)
}
func (m *DeviceSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSet.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSet proto.InternalMessageInfo

func (m *DeviceSet) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Device struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=Active,proto3" json:"Active,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{1}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Device) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Device) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Device) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=Active,proto3" json:"Active,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceRequest) Reset()         { *m = CreateDeviceRequest{} }
func (m *CreateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequest) ProtoMessage()    {}
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{2}
}

func (m *CreateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequest.Unmarshal(m, b)
}
func (m *CreateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequest.Merge(m, src)
}
func (m *CreateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequest.Size(m)
}
func (m *CreateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequest proto.InternalMessageInfo

func (m *CreateDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateDeviceRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CreateDeviceRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateDeviceResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceResponse) Reset()         { *m = CreateDeviceResponse{} }
func (m *CreateDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceResponse) ProtoMessage()    {}
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{3}
}

func (m *CreateDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceResponse.Unmarshal(m, b)
}
func (m *CreateDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceResponse.Merge(m, src)
}
func (m *CreateDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceResponse.Size(m)
}
func (m *CreateDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceResponse proto.InternalMessageInfo

func (m *CreateDeviceResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{4}
}

func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(m, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeleteDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteDeviceResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{5}
}

func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(m, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

func (m *DeleteDeviceResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ListDevicesRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevicesRequest) Reset()         { *m = ListDevicesRequest{} }
func (m *ListDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDevicesRequest) ProtoMessage()    {}
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{6}
}

func (m *ListDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesRequest.Unmarshal(m, b)
}
func (m *ListDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesRequest.Marshal(b, m, deterministic)
}
func (m *ListDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesRequest.Merge(m, src)
}
func (m *ListDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDevicesRequest.Size(m)
}
func (m *ListDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesRequest proto.InternalMessageInfo

func (m *ListDevicesRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ListDevicesResponse struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDevicesResponse) Reset()         { *m = ListDevicesResponse{} }
func (m *ListDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDevicesResponse) ProtoMessage()    {}
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{7}
}

func (m *ListDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesResponse.Unmarshal(m, b)
}
func (m *ListDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesResponse.Marshal(b, m, deterministic)
}
func (m *ListDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesResponse.Merge(m, src)
}
func (m *ListDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDevicesResponse.Size(m)
}
func (m *ListDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesResponse proto.InternalMessageInfo

func (m *ListDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceRequest) Reset()         { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()    {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{8}
}

func (m *GetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceRequest.Unmarshal(m, b)
}
func (m *GetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceRequest.Merge(m, src)
}
func (m *GetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceRequest.Size(m)
}
func (m *GetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceRequest proto.InternalMessageInfo

func (m *GetDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GetDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetDeviceResponse struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceResponse) Reset()         { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()    {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{9}
}

func (m *GetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceResponse.Unmarshal(m, b)
}
func (m *GetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceResponse.Merge(m, src)
}
func (m *GetDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceResponse.Size(m)
}
func (m *GetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceResponse proto.InternalMessageInfo

func (m *GetDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type EnableDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableDeviceRequest) Reset()         { *m = EnableDeviceRequest{} }
func (m *EnableDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*EnableDeviceRequest) ProtoMessage()    {}
func (*EnableDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{10}
}

func (m *EnableDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableDeviceRequest.Unmarshal(m, b)
}
func (m *EnableDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableDeviceRequest.Marshal(b, m, deterministic)
}
func (m *EnableDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableDeviceRequest.Merge(m, src)
}
func (m *EnableDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_EnableDeviceRequest.Size(m)
}
func (m *EnableDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableDeviceRequest proto.InternalMessageInfo

func (m *EnableDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *EnableDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type EnableDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableDeviceResponse) Reset()         { *m = EnableDeviceResponse{} }
func (m *EnableDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*EnableDeviceResponse) ProtoMessage()    {}
func (*EnableDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{11}
}

func (m *EnableDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableDeviceResponse.Unmarshal(m, b)
}
func (m *EnableDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableDeviceResponse.Marshal(b, m, deterministic)
}
func (m *EnableDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableDeviceResponse.Merge(m, src)
}
func (m *EnableDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_EnableDeviceResponse.Size(m)
}
func (m *EnableDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableDeviceResponse proto.InternalMessageInfo

type DisableDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableDeviceRequest) Reset()         { *m = DisableDeviceRequest{} }
func (m *DisableDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DisableDeviceRequest) ProtoMessage()    {}
func (*DisableDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{12}
}

func (m *DisableDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableDeviceRequest.Unmarshal(m, b)
}
func (m *DisableDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DisableDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableDeviceRequest.Merge(m, src)
}
func (m *DisableDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DisableDeviceRequest.Size(m)
}
func (m *DisableDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableDeviceRequest proto.InternalMessageInfo

func (m *DisableDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DisableDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DisableDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableDeviceResponse) Reset()         { *m = DisableDeviceResponse{} }
func (m *DisableDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DisableDeviceResponse) ProtoMessage()    {}
func (*DisableDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{13}
}

func (m *DisableDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableDeviceResponse.Unmarshal(m, b)
}
func (m *DisableDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DisableDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableDeviceResponse.Merge(m, src)
}
func (m *DisableDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DisableDeviceResponse.Size(m)
}
func (m *DisableDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableDeviceResponse proto.InternalMessageInfo

type ChangeDevicePasswordRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDevicePasswordRequest) Reset()         { *m = ChangeDevicePasswordRequest{} }
func (m *ChangeDevicePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeDevicePasswordRequest) ProtoMessage()    {}
func (*ChangeDevicePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{14}
}

func (m *ChangeDevicePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDevicePasswordRequest.Unmarshal(m, b)
}
func (m *ChangeDevicePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDevicePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangeDevicePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDevicePasswordRequest.Merge(m, src)
}
func (m *ChangeDevicePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeDevicePasswordRequest.Size(m)
}
func (m *ChangeDevicePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDevicePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDevicePasswordRequest proto.InternalMessageInfo

func (m *ChangeDevicePasswordRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ChangeDevicePasswordRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ChangeDevicePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangeDevicePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDevicePasswordResponse) Reset()         { *m = ChangeDevicePasswordResponse{} }
func (m *ChangeDevicePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeDevicePasswordResponse) ProtoMessage()    {}
func (*ChangeDevicePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{15}
}

func (m *ChangeDevicePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDevicePasswordResponse.Unmarshal(m, b)
}
func (m *ChangeDevicePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDevicePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangeDevicePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDevicePasswordResponse.Merge(m, src)
}
func (m *ChangeDevicePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeDevicePasswordResponse.Size(m)
}
func (m *ChangeDevicePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDevicePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDevicePasswordResponse proto.InternalMessageInfo

type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{16}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_00212fb1f9d3bf1c, []int{17}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*DeviceSet)(nil), "api.DeviceSet")
	proto.RegisterType((*Device)(nil), "api.Device")
	proto.RegisterType((*CreateDeviceRequest)(nil), "api.CreateDeviceRequest")
	proto.RegisterType((*CreateDeviceResponse)(nil), "api.CreateDeviceResponse")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "api.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "api.DeleteDeviceResponse")
	proto.RegisterType((*ListDevicesRequest)(nil), "api.ListDevicesRequest")
	proto.RegisterType((*ListDevicesResponse)(nil), "api.ListDevicesResponse")
	proto.RegisterType((*GetDeviceRequest)(nil), "api.GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "api.GetDeviceResponse")
	proto.RegisterType((*EnableDeviceRequest)(nil), "api.EnableDeviceRequest")
	proto.RegisterType((*EnableDeviceResponse)(nil), "api.EnableDeviceResponse")
	proto.RegisterType((*DisableDeviceRequest)(nil), "api.DisableDeviceRequest")
	proto.RegisterType((*DisableDeviceResponse)(nil), "api.DisableDeviceResponse")
	proto.RegisterType((*ChangeDevicePasswordRequest)(nil), "api.ChangeDevicePasswordRequest")
	proto.RegisterType((*ChangeDevicePasswordResponse)(nil), "api.ChangeDevicePasswordResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "api.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "api.ShutdownResponse")
}

func init() { proto.RegisterFile("api.proto", fileDescriptor_00212fb1f9d3bf1c) }

var fileDescriptor_00212fb1f9d3bf1c = []byte{
	// 528 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x95, 0xcd, 0x6e, 0xd3, 0x40,
	0x10, 0xc7, 0x71, 0x9c, 0x86, 0x78, 0x52, 0xa0, 0x9d, 0x38, 0xa9, 0x31, 0x15, 0x32, 0x46, 0xa0,
	0x88, 0x43, 0x0f, 0xe1, 0x52, 0xa0, 0x07, 0xa2, 0x18, 0x50, 0x25, 0x14, 0x50, 0x2a, 0x71, 0xe1,
	0xe4, 0x36, 0x23, 0x6a, 0xa9, 0xd8, 0xc6, 0xeb, 0x36, 0xe2, 0x3d, 0x78, 0x5c, 0x0e, 0x28, 0xbb,
	0xe3, 0xc4, 0x76, 0x37, 0x55, 0xc8, 0xcd, 0x3b, 0x3b, 0x33, 0xff, 0xf9, 0xf8, 0xad, 0x0c, 0x56,
	0x98, 0x46, 0x47, 0x69, 0x96, 0xe4, 0x09, 0x9a, 0x61, 0x1a, 0xf9, 0x43, 0xb0, 0x02, 0xba, 0x89,
	0x2e, 0xe8, 0x8c, 0x72, 0x7c, 0x01, 0xf7, 0xd5, 0x41, 0x38, 0x86, 0x67, 0x0e, 0x3a, 0xc3, 0xce,
	0xd1, 0xc2, 0x5d, 0xd9, 0xa6, 0xc5, 0x9d, 0xff, 0xc7, 0x80, 0x96, 0xfa, 0x46, 0x1b, 0x76, 0xbe,
	0xcc, 0x63, 0xca, 0x1c, 0xc3, 0x33, 0x06, 0xd6, 0x54, 0x1d, 0xf0, 0x21, 0x34, 0x4e, 0x03, 0xa7,
	0x21, 0x4d, 0x8d, 0xd3, 0x00, 0x11, 0x9a, 0x93, 0xf0, 0x27, 0x39, 0xa6, 0xb4, 0xc8, 0x6f, 0xec,
	0x43, 0x6b, 0x74, 0x91, 0x47, 0x37, 0xe4, 0x34, 0x3d, 0x63, 0xd0, 0x9e, 0xf2, 0x09, 0x0f, 0xc1,
	0x1a, 0x67, 0x14, 0xe6, 0x34, 0x1b, 0xe5, 0xce, 0x8e, 0x67, 0x0c, 0xcc, 0xe9, 0xca, 0x80, 0x2e,
	0xb4, 0xbf, 0x86, 0x42, 0xcc, 0x93, 0x6c, 0xe6, 0xb4, 0x64, 0xb6, 0xe5, 0xd9, 0x17, 0xd0, 0x55,
	0x8e, 0x5c, 0x2f, 0xfd, 0xba, 0x26, 0x91, 0xaf, 0x29, 0xb1, 0x28, 0xa9, 0xa1, 0x2d, 0xc9, 0xac,
	0x94, 0x54, 0x16, 0x6d, 0xd6, 0x44, 0x5f, 0x82, 0x5d, 0x15, 0x15, 0x69, 0x12, 0x0b, 0xe2, 0x11,
	0x18, 0xc5, 0x08, 0xfc, 0x77, 0xd0, 0x0d, 0xe8, 0x8a, 0x36, 0x2b, 0xae, 0x36, 0xbf, 0x85, 0x48,
	0x35, 0x78, 0x8d, 0xc8, 0x2b, 0xc0, 0xcf, 0x91, 0xc8, 0x79, 0x4f, 0x77, 0x6a, 0xf8, 0x27, 0xd0,
	0xad, 0xf8, 0x72, 0xca, 0x0d, 0x11, 0x38, 0x86, 0xbd, 0x4f, 0x94, 0x6f, 0xd3, 0xcb, 0x31, 0xec,
	0x97, 0x22, 0x59, 0xf5, 0x79, 0x01, 0x94, 0x8c, 0xad, 0x89, 0xf2, 0xd5, 0x62, 0x84, 0x1f, 0xe2,
	0xf0, 0xfc, 0x6a, 0xab, 0x11, 0xf6, 0xc1, 0xae, 0x06, 0x2b, 0x65, 0xff, 0x04, 0xec, 0x20, 0x12,
	0xdb, 0x66, 0x3d, 0x80, 0x5e, 0x2d, 0x9a, 0xd3, 0x12, 0x3c, 0x19, 0x5f, 0x86, 0xf1, 0x0f, 0xb6,
	0x17, 0xb8, 0xfc, 0x57, 0x76, 0xf4, 0xa0, 0x33, 0xa1, 0xf9, 0x12, 0x3d, 0xf5, 0x7a, 0xca, 0x26,
	0xff, 0x29, 0x1c, 0xea, 0x65, 0xb8, 0x8c, 0x7d, 0x78, 0x74, 0x76, 0x79, 0x9d, 0xcf, 0x92, 0x79,
	0xcc, 0xd2, 0x3e, 0xc2, 0xde, 0xca, 0xa4, 0xdc, 0x86, 0x7f, 0x4d, 0x68, 0x7f, 0x23, 0x91, 0x46,
	0x61, 0xf6, 0x1b, 0xc7, 0xb0, 0x5b, 0x26, 0x1a, 0x1d, 0xb9, 0x0b, 0xcd, 0xcb, 0x72, 0x1f, 0x6b,
	0x6e, 0x78, 0xa1, 0x63, 0xd8, 0x2d, 0x13, 0xcb, 0x49, 0x34, 0x2f, 0x80, 0x93, 0x68, 0xf1, 0x7e,
	0x0f, 0x9d, 0x12, 0xa2, 0x78, 0x20, 0x3d, 0x6f, 0x03, 0xee, 0x3a, 0xb7, 0x2f, 0x38, 0xc3, 0x5b,
	0xb0, 0x96, 0xb0, 0x61, 0x4f, 0xba, 0xd5, 0xb1, 0x75, 0xfb, 0x75, 0xf3, 0xaa, 0x85, 0x32, 0x31,
	0xdc, 0x82, 0x86, 0x40, 0x6e, 0x41, 0x87, 0x17, 0x7e, 0x84, 0x07, 0x15, 0x40, 0x90, 0xdb, 0xd5,
	0x20, 0xe7, 0xba, 0xba, 0x2b, 0xce, 0xf3, 0x1d, 0x6c, 0xdd, 0xa2, 0xd1, 0x53, 0x2b, 0x58, 0x8f,
	0x9a, 0xfb, 0xec, 0x0e, 0x0f, 0x5e, 0xff, 0x08, 0x9a, 0x93, 0x64, 0x46, 0xf8, 0x06, 0xda, 0x05,
	0x1a, 0x68, 0xcb, 0xb0, 0x1a, 0x3c, 0x6e, 0xaf, 0x66, 0x65, 0xcc, 0xee, 0x9d, 0xb7, 0xe4, 0x2f,
	0xe5, 0xf5, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x7b, 0x22, 0xf4, 0x5f, 0x5f, 0x06, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VespiaryClient is the client API for Vespiary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VespiaryClient interface {
	CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	EnableDevice(ctx context.Context, in *EnableDeviceRequest, opts ...grpc.CallOption) (*EnableDeviceResponse, error)
	DisableDevice(ctx context.Context, in *DisableDeviceRequest, opts ...grpc.CallOption) (*DisableDeviceResponse, error)
	ChangeDevicePassword(ctx context.Context, in *ChangeDevicePasswordRequest, opts ...grpc.CallOption) (*ChangeDevicePasswordResponse, error)
}

type vespiaryClient struct {
	cc *grpc.ClientConn
}

func NewVespiaryClient(cc *grpc.ClientConn) VespiaryClient {
	return &vespiaryClient{cc}
}

func (c *vespiaryClient) CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	out := new(CreateDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/CreateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) EnableDevice(ctx context.Context, in *EnableDeviceRequest, opts ...grpc.CallOption) (*EnableDeviceResponse, error) {
	out := new(EnableDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/EnableDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) DisableDevice(ctx context.Context, in *DisableDeviceRequest, opts ...grpc.CallOption) (*DisableDeviceResponse, error) {
	out := new(DisableDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/DisableDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) ChangeDevicePassword(ctx context.Context, in *ChangeDevicePasswordRequest, opts ...grpc.CallOption) (*ChangeDevicePasswordResponse, error) {
	out := new(ChangeDevicePasswordResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/ChangeDevicePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VespiaryServer is the server API for Vespiary service.
type VespiaryServer interface {
	CreateDevice(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	EnableDevice(context.Context, *EnableDeviceRequest) (*EnableDeviceResponse, error)
	DisableDevice(context.Context, *DisableDeviceRequest) (*DisableDeviceResponse, error)
	ChangeDevicePassword(context.Context, *ChangeDevicePasswordRequest) (*ChangeDevicePasswordResponse, error)
}

// UnimplementedVespiaryServer can be embedded to have forward compatible implementations.
type UnimplementedVespiaryServer struct {
}

func (*UnimplementedVespiaryServer) CreateDevice(ctx context.Context, req *CreateDeviceRequest) (*CreateDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevice not implemented")
}
func (*UnimplementedVespiaryServer) DeleteDevice(ctx context.Context, req *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (*UnimplementedVespiaryServer) ListDevices(ctx context.Context, req *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (*UnimplementedVespiaryServer) GetDevice(ctx context.Context, req *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (*UnimplementedVespiaryServer) EnableDevice(ctx context.Context, req *EnableDeviceRequest) (*EnableDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableDevice not implemented")
}
func (*UnimplementedVespiaryServer) DisableDevice(ctx context.Context, req *DisableDeviceRequest) (*DisableDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableDevice not implemented")
}
func (*UnimplementedVespiaryServer) ChangeDevicePassword(ctx context.Context, req *ChangeDevicePasswordRequest) (*ChangeDevicePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDevicePassword not implemented")
}

func RegisterVespiaryServer(s *grpc.Server, srv VespiaryServer) {
	s.RegisterService(&_Vespiary_serviceDesc, srv)
}

func _Vespiary_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/CreateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).CreateDevice(ctx, req.(*CreateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_EnableDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).EnableDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/EnableDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).EnableDevice(ctx, req.(*EnableDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_DisableDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).DisableDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/DisableDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).DisableDevice(ctx, req.(*DisableDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_ChangeDevicePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDevicePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).ChangeDevicePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/ChangeDevicePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).ChangeDevicePassword(ctx, req.(*ChangeDevicePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vespiary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Vespiary",
	HandlerType: (*VespiaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDevice",
			Handler:    _Vespiary_CreateDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _Vespiary_DeleteDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _Vespiary_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _Vespiary_GetDevice_Handler,
		},
		{
			MethodName: "EnableDevice",
			Handler:    _Vespiary_EnableDevice_Handler,
		},
		{
			MethodName: "DisableDevice",
			Handler:    _Vespiary_DisableDevice_Handler,
		},
		{
			MethodName: "ChangeDevicePassword",
			Handler:    _Vespiary_ChangeDevicePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/api.Node/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

// UnimplementedNodeServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (*UnimplementedNodeServer) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _Node_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api.proto",
}
