// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vespiary.proto

package api

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Account struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Principals           []string `protobuf:"bytes,3,rep,name=Principals,proto3" json:"Principals,omitempty"`
	DeviceUsernames      []string `protobuf:"bytes,4,rep,name=DeviceUsernames,proto3" json:"DeviceUsernames,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{0}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Account) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Account) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *Account) GetDeviceUsernames() []string {
	if m != nil {
		return m.DeviceUsernames
	}
	return nil
}

func (m *Account) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type AccountSet struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *AccountSet) Reset()         { *m = AccountSet{} }
func (m *AccountSet) String() string { return proto.CompactTextString(m) }
func (*AccountSet) ProtoMessage()    {}
func (*AccountSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{1}
}

func (m *AccountSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountSet.Unmarshal(m, b)
}
func (m *AccountSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountSet.Marshal(b, m, deterministic)
}
func (m *AccountSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountSet.Merge(m, src)
}
func (m *AccountSet) XXX_Size() int {
	return xxx_messageInfo_AccountSet.Size(m)
}
func (m *AccountSet) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountSet.DiscardUnknown(m)
}

var xxx_messageInfo_AccountSet proto.InternalMessageInfo

func (m *AccountSet) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type DeviceSet struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *DeviceSet) Reset()         { *m = DeviceSet{} }
func (m *DeviceSet) String() string { return proto.CompactTextString(m) }
func (*DeviceSet) ProtoMessage()    {}
func (*DeviceSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{2}
}

func (m *DeviceSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceSet.Unmarshal(m, b)
}
func (m *DeviceSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceSet.Marshal(b, m, deterministic)
}
func (m *DeviceSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceSet.Merge(m, src)
}
func (m *DeviceSet) XXX_Size() int {
	return xxx_messageInfo_DeviceSet.Size(m)
}
func (m *DeviceSet) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceSet.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceSet proto.InternalMessageInfo

func (m *DeviceSet) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type Device struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=Active,proto3" json:"Active,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Password             string   `protobuf:"bytes,6,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{3}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *Device) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *Device) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Device) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *Device) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *Device) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Active               bool     `protobuf:"varint,3,opt,name=Active,proto3" json:"Active,omitempty"`
	Password             string   `protobuf:"bytes,4,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceRequest) Reset()         { *m = CreateDeviceRequest{} }
func (m *CreateDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceRequest) ProtoMessage()    {}
func (*CreateDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{4}
}

func (m *CreateDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceRequest.Unmarshal(m, b)
}
func (m *CreateDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceRequest.Marshal(b, m, deterministic)
}
func (m *CreateDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceRequest.Merge(m, src)
}
func (m *CreateDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceRequest.Size(m)
}
func (m *CreateDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceRequest proto.InternalMessageInfo

func (m *CreateDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *CreateDeviceRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateDeviceRequest) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *CreateDeviceRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateDeviceResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateDeviceResponse) Reset()         { *m = CreateDeviceResponse{} }
func (m *CreateDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*CreateDeviceResponse) ProtoMessage()    {}
func (*CreateDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{5}
}

func (m *CreateDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateDeviceResponse.Unmarshal(m, b)
}
func (m *CreateDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateDeviceResponse.Marshal(b, m, deterministic)
}
func (m *CreateDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateDeviceResponse.Merge(m, src)
}
func (m *CreateDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_CreateDeviceResponse.Size(m)
}
func (m *CreateDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateDeviceResponse proto.InternalMessageInfo

func (m *CreateDeviceResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceRequest) Reset()         { *m = DeleteDeviceRequest{} }
func (m *DeleteDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceRequest) ProtoMessage()    {}
func (*DeleteDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{6}
}

func (m *DeleteDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceRequest.Unmarshal(m, b)
}
func (m *DeleteDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceRequest.Merge(m, src)
}
func (m *DeleteDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceRequest.Size(m)
}
func (m *DeleteDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceRequest proto.InternalMessageInfo

func (m *DeleteDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeleteDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteDeviceResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteDeviceResponse) Reset()         { *m = DeleteDeviceResponse{} }
func (m *DeleteDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteDeviceResponse) ProtoMessage()    {}
func (*DeleteDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{7}
}

func (m *DeleteDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteDeviceResponse.Unmarshal(m, b)
}
func (m *DeleteDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DeleteDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteDeviceResponse.Merge(m, src)
}
func (m *DeleteDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteDeviceResponse.Size(m)
}
func (m *DeleteDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteDeviceResponse proto.InternalMessageInfo

func (m *DeleteDeviceResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ListDevicesRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListDevicesRequest) Reset()         { *m = ListDevicesRequest{} }
func (m *ListDevicesRequest) String() string { return proto.CompactTextString(m) }
func (*ListDevicesRequest) ProtoMessage()    {}
func (*ListDevicesRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{8}
}

func (m *ListDevicesRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesRequest.Unmarshal(m, b)
}
func (m *ListDevicesRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesRequest.Marshal(b, m, deterministic)
}
func (m *ListDevicesRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesRequest.Merge(m, src)
}
func (m *ListDevicesRequest) XXX_Size() int {
	return xxx_messageInfo_ListDevicesRequest.Size(m)
}
func (m *ListDevicesRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesRequest proto.InternalMessageInfo

func (m *ListDevicesRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type ListDevicesResponse struct {
	Devices              []*Device `protobuf:"bytes,1,rep,name=Devices,proto3" json:"Devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ListDevicesResponse) Reset()         { *m = ListDevicesResponse{} }
func (m *ListDevicesResponse) String() string { return proto.CompactTextString(m) }
func (*ListDevicesResponse) ProtoMessage()    {}
func (*ListDevicesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{9}
}

func (m *ListDevicesResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListDevicesResponse.Unmarshal(m, b)
}
func (m *ListDevicesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListDevicesResponse.Marshal(b, m, deterministic)
}
func (m *ListDevicesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListDevicesResponse.Merge(m, src)
}
func (m *ListDevicesResponse) XXX_Size() int {
	return xxx_messageInfo_ListDevicesResponse.Size(m)
}
func (m *ListDevicesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListDevicesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListDevicesResponse proto.InternalMessageInfo

func (m *ListDevicesResponse) GetDevices() []*Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type GetDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceRequest) Reset()         { *m = GetDeviceRequest{} }
func (m *GetDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*GetDeviceRequest) ProtoMessage()    {}
func (*GetDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{10}
}

func (m *GetDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceRequest.Unmarshal(m, b)
}
func (m *GetDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceRequest.Marshal(b, m, deterministic)
}
func (m *GetDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceRequest.Merge(m, src)
}
func (m *GetDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_GetDeviceRequest.Size(m)
}
func (m *GetDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceRequest proto.InternalMessageInfo

func (m *GetDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *GetDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type GetDeviceResponse struct {
	Device               *Device  `protobuf:"bytes,1,opt,name=Device,proto3" json:"Device,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetDeviceResponse) Reset()         { *m = GetDeviceResponse{} }
func (m *GetDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*GetDeviceResponse) ProtoMessage()    {}
func (*GetDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{11}
}

func (m *GetDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetDeviceResponse.Unmarshal(m, b)
}
func (m *GetDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetDeviceResponse.Marshal(b, m, deterministic)
}
func (m *GetDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetDeviceResponse.Merge(m, src)
}
func (m *GetDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_GetDeviceResponse.Size(m)
}
func (m *GetDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetDeviceResponse proto.InternalMessageInfo

func (m *GetDeviceResponse) GetDevice() *Device {
	if m != nil {
		return m.Device
	}
	return nil
}

type EnableDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableDeviceRequest) Reset()         { *m = EnableDeviceRequest{} }
func (m *EnableDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*EnableDeviceRequest) ProtoMessage()    {}
func (*EnableDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{12}
}

func (m *EnableDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableDeviceRequest.Unmarshal(m, b)
}
func (m *EnableDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableDeviceRequest.Marshal(b, m, deterministic)
}
func (m *EnableDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableDeviceRequest.Merge(m, src)
}
func (m *EnableDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_EnableDeviceRequest.Size(m)
}
func (m *EnableDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_EnableDeviceRequest proto.InternalMessageInfo

func (m *EnableDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *EnableDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type EnableDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *EnableDeviceResponse) Reset()         { *m = EnableDeviceResponse{} }
func (m *EnableDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*EnableDeviceResponse) ProtoMessage()    {}
func (*EnableDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{13}
}

func (m *EnableDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EnableDeviceResponse.Unmarshal(m, b)
}
func (m *EnableDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EnableDeviceResponse.Marshal(b, m, deterministic)
}
func (m *EnableDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EnableDeviceResponse.Merge(m, src)
}
func (m *EnableDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_EnableDeviceResponse.Size(m)
}
func (m *EnableDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_EnableDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_EnableDeviceResponse proto.InternalMessageInfo

type DisableDeviceRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableDeviceRequest) Reset()         { *m = DisableDeviceRequest{} }
func (m *DisableDeviceRequest) String() string { return proto.CompactTextString(m) }
func (*DisableDeviceRequest) ProtoMessage()    {}
func (*DisableDeviceRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{14}
}

func (m *DisableDeviceRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableDeviceRequest.Unmarshal(m, b)
}
func (m *DisableDeviceRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableDeviceRequest.Marshal(b, m, deterministic)
}
func (m *DisableDeviceRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableDeviceRequest.Merge(m, src)
}
func (m *DisableDeviceRequest) XXX_Size() int {
	return xxx_messageInfo_DisableDeviceRequest.Size(m)
}
func (m *DisableDeviceRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableDeviceRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DisableDeviceRequest proto.InternalMessageInfo

func (m *DisableDeviceRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DisableDeviceRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DisableDeviceResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DisableDeviceResponse) Reset()         { *m = DisableDeviceResponse{} }
func (m *DisableDeviceResponse) String() string { return proto.CompactTextString(m) }
func (*DisableDeviceResponse) ProtoMessage()    {}
func (*DisableDeviceResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{15}
}

func (m *DisableDeviceResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DisableDeviceResponse.Unmarshal(m, b)
}
func (m *DisableDeviceResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DisableDeviceResponse.Marshal(b, m, deterministic)
}
func (m *DisableDeviceResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DisableDeviceResponse.Merge(m, src)
}
func (m *DisableDeviceResponse) XXX_Size() int {
	return xxx_messageInfo_DisableDeviceResponse.Size(m)
}
func (m *DisableDeviceResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DisableDeviceResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DisableDeviceResponse proto.InternalMessageInfo

type ChangeDevicePasswordRequest struct {
	Owner                string   `protobuf:"bytes,1,opt,name=Owner,proto3" json:"Owner,omitempty"`
	ID                   string   `protobuf:"bytes,2,opt,name=ID,proto3" json:"ID,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=NewPassword,proto3" json:"NewPassword,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDevicePasswordRequest) Reset()         { *m = ChangeDevicePasswordRequest{} }
func (m *ChangeDevicePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*ChangeDevicePasswordRequest) ProtoMessage()    {}
func (*ChangeDevicePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{16}
}

func (m *ChangeDevicePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDevicePasswordRequest.Unmarshal(m, b)
}
func (m *ChangeDevicePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDevicePasswordRequest.Marshal(b, m, deterministic)
}
func (m *ChangeDevicePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDevicePasswordRequest.Merge(m, src)
}
func (m *ChangeDevicePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_ChangeDevicePasswordRequest.Size(m)
}
func (m *ChangeDevicePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDevicePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDevicePasswordRequest proto.InternalMessageInfo

func (m *ChangeDevicePasswordRequest) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *ChangeDevicePasswordRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ChangeDevicePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

type ChangeDevicePasswordResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ChangeDevicePasswordResponse) Reset()         { *m = ChangeDevicePasswordResponse{} }
func (m *ChangeDevicePasswordResponse) String() string { return proto.CompactTextString(m) }
func (*ChangeDevicePasswordResponse) ProtoMessage()    {}
func (*ChangeDevicePasswordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{17}
}

func (m *ChangeDevicePasswordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ChangeDevicePasswordResponse.Unmarshal(m, b)
}
func (m *ChangeDevicePasswordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ChangeDevicePasswordResponse.Marshal(b, m, deterministic)
}
func (m *ChangeDevicePasswordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ChangeDevicePasswordResponse.Merge(m, src)
}
func (m *ChangeDevicePasswordResponse) XXX_Size() int {
	return xxx_messageInfo_ChangeDevicePasswordResponse.Size(m)
}
func (m *ChangeDevicePasswordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ChangeDevicePasswordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ChangeDevicePasswordResponse proto.InternalMessageInfo

type CreateAccountRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Principals           []string `protobuf:"bytes,2,rep,name=Principals,proto3" json:"Principals,omitempty"`
	DeviceUsernames      []string `protobuf:"bytes,3,rep,name=DeviceUsernames,proto3" json:"DeviceUsernames,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountRequest) Reset()         { *m = CreateAccountRequest{} }
func (m *CreateAccountRequest) String() string { return proto.CompactTextString(m) }
func (*CreateAccountRequest) ProtoMessage()    {}
func (*CreateAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{18}
}

func (m *CreateAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountRequest.Unmarshal(m, b)
}
func (m *CreateAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountRequest.Marshal(b, m, deterministic)
}
func (m *CreateAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountRequest.Merge(m, src)
}
func (m *CreateAccountRequest) XXX_Size() int {
	return xxx_messageInfo_CreateAccountRequest.Size(m)
}
func (m *CreateAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountRequest proto.InternalMessageInfo

func (m *CreateAccountRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CreateAccountRequest) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *CreateAccountRequest) GetDeviceUsernames() []string {
	if m != nil {
		return m.DeviceUsernames
	}
	return nil
}

type CreateAccountResponse struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateAccountResponse) Reset()         { *m = CreateAccountResponse{} }
func (m *CreateAccountResponse) String() string { return proto.CompactTextString(m) }
func (*CreateAccountResponse) ProtoMessage()    {}
func (*CreateAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{19}
}

func (m *CreateAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateAccountResponse.Unmarshal(m, b)
}
func (m *CreateAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateAccountResponse.Marshal(b, m, deterministic)
}
func (m *CreateAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateAccountResponse.Merge(m, src)
}
func (m *CreateAccountResponse) XXX_Size() int {
	return xxx_messageInfo_CreateAccountResponse.Size(m)
}
func (m *CreateAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateAccountResponse proto.InternalMessageInfo

func (m *CreateAccountResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteAccountRequest struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountRequest) Reset()         { *m = DeleteAccountRequest{} }
func (m *DeleteAccountRequest) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountRequest) ProtoMessage()    {}
func (*DeleteAccountRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{20}
}

func (m *DeleteAccountRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountRequest.Unmarshal(m, b)
}
func (m *DeleteAccountRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountRequest.Marshal(b, m, deterministic)
}
func (m *DeleteAccountRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountRequest.Merge(m, src)
}
func (m *DeleteAccountRequest) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountRequest.Size(m)
}
func (m *DeleteAccountRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountRequest proto.InternalMessageInfo

func (m *DeleteAccountRequest) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type DeleteAccountResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeleteAccountResponse) Reset()         { *m = DeleteAccountResponse{} }
func (m *DeleteAccountResponse) String() string { return proto.CompactTextString(m) }
func (*DeleteAccountResponse) ProtoMessage()    {}
func (*DeleteAccountResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{21}
}

func (m *DeleteAccountResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeleteAccountResponse.Unmarshal(m, b)
}
func (m *DeleteAccountResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeleteAccountResponse.Marshal(b, m, deterministic)
}
func (m *DeleteAccountResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeleteAccountResponse.Merge(m, src)
}
func (m *DeleteAccountResponse) XXX_Size() int {
	return xxx_messageInfo_DeleteAccountResponse.Size(m)
}
func (m *DeleteAccountResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DeleteAccountResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DeleteAccountResponse proto.InternalMessageInfo

type ListAccountsRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListAccountsRequest) Reset()         { *m = ListAccountsRequest{} }
func (m *ListAccountsRequest) String() string { return proto.CompactTextString(m) }
func (*ListAccountsRequest) ProtoMessage()    {}
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{22}
}

func (m *ListAccountsRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsRequest.Unmarshal(m, b)
}
func (m *ListAccountsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsRequest.Marshal(b, m, deterministic)
}
func (m *ListAccountsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsRequest.Merge(m, src)
}
func (m *ListAccountsRequest) XXX_Size() int {
	return xxx_messageInfo_ListAccountsRequest.Size(m)
}
func (m *ListAccountsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsRequest proto.InternalMessageInfo

type ListAccountsResponse struct {
	Accounts             []*Account `protobuf:"bytes,1,rep,name=Accounts,proto3" json:"Accounts,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *ListAccountsResponse) Reset()         { *m = ListAccountsResponse{} }
func (m *ListAccountsResponse) String() string { return proto.CompactTextString(m) }
func (*ListAccountsResponse) ProtoMessage()    {}
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{23}
}

func (m *ListAccountsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListAccountsResponse.Unmarshal(m, b)
}
func (m *ListAccountsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListAccountsResponse.Marshal(b, m, deterministic)
}
func (m *ListAccountsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListAccountsResponse.Merge(m, src)
}
func (m *ListAccountsResponse) XXX_Size() int {
	return xxx_messageInfo_ListAccountsResponse.Size(m)
}
func (m *ListAccountsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListAccountsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListAccountsResponse proto.InternalMessageInfo

func (m *ListAccountsResponse) GetAccounts() []*Account {
	if m != nil {
		return m.Accounts
	}
	return nil
}

type ShutdownRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownRequest) Reset()         { *m = ShutdownRequest{} }
func (m *ShutdownRequest) String() string { return proto.CompactTextString(m) }
func (*ShutdownRequest) ProtoMessage()    {}
func (*ShutdownRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{24}
}

func (m *ShutdownRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownRequest.Unmarshal(m, b)
}
func (m *ShutdownRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownRequest.Marshal(b, m, deterministic)
}
func (m *ShutdownRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownRequest.Merge(m, src)
}
func (m *ShutdownRequest) XXX_Size() int {
	return xxx_messageInfo_ShutdownRequest.Size(m)
}
func (m *ShutdownRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownRequest proto.InternalMessageInfo

type ShutdownResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ShutdownResponse) Reset()         { *m = ShutdownResponse{} }
func (m *ShutdownResponse) String() string { return proto.CompactTextString(m) }
func (*ShutdownResponse) ProtoMessage()    {}
func (*ShutdownResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{25}
}

func (m *ShutdownResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ShutdownResponse.Unmarshal(m, b)
}
func (m *ShutdownResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ShutdownResponse.Marshal(b, m, deterministic)
}
func (m *ShutdownResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ShutdownResponse.Merge(m, src)
}
func (m *ShutdownResponse) XXX_Size() int {
	return xxx_messageInfo_ShutdownResponse.Size(m)
}
func (m *ShutdownResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ShutdownResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ShutdownResponse proto.InternalMessageInfo

type VespiaryEventAttribute struct {
	Key                  string   `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *VespiaryEventAttribute) Reset()         { *m = VespiaryEventAttribute{} }
func (m *VespiaryEventAttribute) String() string { return proto.CompactTextString(m) }
func (*VespiaryEventAttribute) ProtoMessage()    {}
func (*VespiaryEventAttribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{26}
}

func (m *VespiaryEventAttribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VespiaryEventAttribute.Unmarshal(m, b)
}
func (m *VespiaryEventAttribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VespiaryEventAttribute.Marshal(b, m, deterministic)
}
func (m *VespiaryEventAttribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VespiaryEventAttribute.Merge(m, src)
}
func (m *VespiaryEventAttribute) XXX_Size() int {
	return xxx_messageInfo_VespiaryEventAttribute.Size(m)
}
func (m *VespiaryEventAttribute) XXX_DiscardUnknown() {
	xxx_messageInfo_VespiaryEventAttribute.DiscardUnknown(m)
}

var xxx_messageInfo_VespiaryEventAttribute proto.InternalMessageInfo

func (m *VespiaryEventAttribute) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *VespiaryEventAttribute) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type VespiaryAuditEvent struct {
	Timestamp            int64                     `protobuf:"varint,1,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Tenant               string                    `protobuf:"bytes,2,opt,name=Tenant,proto3" json:"Tenant,omitempty"`
	Kind                 string                    `protobuf:"bytes,3,opt,name=Kind,proto3" json:"Kind,omitempty"`
	Attributes           []*VespiaryEventAttribute `protobuf:"bytes,4,rep,name=Attributes,proto3" json:"Attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *VespiaryAuditEvent) Reset()         { *m = VespiaryAuditEvent{} }
func (m *VespiaryAuditEvent) String() string { return proto.CompactTextString(m) }
func (*VespiaryAuditEvent) ProtoMessage()    {}
func (*VespiaryAuditEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{27}
}

func (m *VespiaryAuditEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VespiaryAuditEvent.Unmarshal(m, b)
}
func (m *VespiaryAuditEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VespiaryAuditEvent.Marshal(b, m, deterministic)
}
func (m *VespiaryAuditEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VespiaryAuditEvent.Merge(m, src)
}
func (m *VespiaryAuditEvent) XXX_Size() int {
	return xxx_messageInfo_VespiaryAuditEvent.Size(m)
}
func (m *VespiaryAuditEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_VespiaryAuditEvent.DiscardUnknown(m)
}

var xxx_messageInfo_VespiaryAuditEvent proto.InternalMessageInfo

func (m *VespiaryAuditEvent) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *VespiaryAuditEvent) GetTenant() string {
	if m != nil {
		return m.Tenant
	}
	return ""
}

func (m *VespiaryAuditEvent) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *VespiaryAuditEvent) GetAttributes() []*VespiaryEventAttribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type PutVespiaryEventRequest struct {
	Events               []*VespiaryAuditEvent `protobuf:"bytes,1,rep,name=Events,proto3" json:"Events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PutVespiaryEventRequest) Reset()         { *m = PutVespiaryEventRequest{} }
func (m *PutVespiaryEventRequest) String() string { return proto.CompactTextString(m) }
func (*PutVespiaryEventRequest) ProtoMessage()    {}
func (*PutVespiaryEventRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{28}
}

func (m *PutVespiaryEventRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVespiaryEventRequest.Unmarshal(m, b)
}
func (m *PutVespiaryEventRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVespiaryEventRequest.Marshal(b, m, deterministic)
}
func (m *PutVespiaryEventRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVespiaryEventRequest.Merge(m, src)
}
func (m *PutVespiaryEventRequest) XXX_Size() int {
	return xxx_messageInfo_PutVespiaryEventRequest.Size(m)
}
func (m *PutVespiaryEventRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVespiaryEventRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PutVespiaryEventRequest proto.InternalMessageInfo

func (m *PutVespiaryEventRequest) GetEvents() []*VespiaryAuditEvent {
	if m != nil {
		return m.Events
	}
	return nil
}

type PutVespiaryEventsResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PutVespiaryEventsResponse) Reset()         { *m = PutVespiaryEventsResponse{} }
func (m *PutVespiaryEventsResponse) String() string { return proto.CompactTextString(m) }
func (*PutVespiaryEventsResponse) ProtoMessage()    {}
func (*PutVespiaryEventsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_efc1ff1bbf92a481, []int{29}
}

func (m *PutVespiaryEventsResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PutVespiaryEventsResponse.Unmarshal(m, b)
}
func (m *PutVespiaryEventsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PutVespiaryEventsResponse.Marshal(b, m, deterministic)
}
func (m *PutVespiaryEventsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PutVespiaryEventsResponse.Merge(m, src)
}
func (m *PutVespiaryEventsResponse) XXX_Size() int {
	return xxx_messageInfo_PutVespiaryEventsResponse.Size(m)
}
func (m *PutVespiaryEventsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PutVespiaryEventsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PutVespiaryEventsResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*Account)(nil), "api.Account")
	proto.RegisterType((*AccountSet)(nil), "api.AccountSet")
	proto.RegisterType((*DeviceSet)(nil), "api.DeviceSet")
	proto.RegisterType((*Device)(nil), "api.Device")
	proto.RegisterType((*CreateDeviceRequest)(nil), "api.CreateDeviceRequest")
	proto.RegisterType((*CreateDeviceResponse)(nil), "api.CreateDeviceResponse")
	proto.RegisterType((*DeleteDeviceRequest)(nil), "api.DeleteDeviceRequest")
	proto.RegisterType((*DeleteDeviceResponse)(nil), "api.DeleteDeviceResponse")
	proto.RegisterType((*ListDevicesRequest)(nil), "api.ListDevicesRequest")
	proto.RegisterType((*ListDevicesResponse)(nil), "api.ListDevicesResponse")
	proto.RegisterType((*GetDeviceRequest)(nil), "api.GetDeviceRequest")
	proto.RegisterType((*GetDeviceResponse)(nil), "api.GetDeviceResponse")
	proto.RegisterType((*EnableDeviceRequest)(nil), "api.EnableDeviceRequest")
	proto.RegisterType((*EnableDeviceResponse)(nil), "api.EnableDeviceResponse")
	proto.RegisterType((*DisableDeviceRequest)(nil), "api.DisableDeviceRequest")
	proto.RegisterType((*DisableDeviceResponse)(nil), "api.DisableDeviceResponse")
	proto.RegisterType((*ChangeDevicePasswordRequest)(nil), "api.ChangeDevicePasswordRequest")
	proto.RegisterType((*ChangeDevicePasswordResponse)(nil), "api.ChangeDevicePasswordResponse")
	proto.RegisterType((*CreateAccountRequest)(nil), "api.CreateAccountRequest")
	proto.RegisterType((*CreateAccountResponse)(nil), "api.CreateAccountResponse")
	proto.RegisterType((*DeleteAccountRequest)(nil), "api.DeleteAccountRequest")
	proto.RegisterType((*DeleteAccountResponse)(nil), "api.DeleteAccountResponse")
	proto.RegisterType((*ListAccountsRequest)(nil), "api.ListAccountsRequest")
	proto.RegisterType((*ListAccountsResponse)(nil), "api.ListAccountsResponse")
	proto.RegisterType((*ShutdownRequest)(nil), "api.ShutdownRequest")
	proto.RegisterType((*ShutdownResponse)(nil), "api.ShutdownResponse")
	proto.RegisterType((*VespiaryEventAttribute)(nil), "api.VespiaryEventAttribute")
	proto.RegisterType((*VespiaryAuditEvent)(nil), "api.VespiaryAuditEvent")
	proto.RegisterType((*PutVespiaryEventRequest)(nil), "api.PutVespiaryEventRequest")
	proto.RegisterType((*PutVespiaryEventsResponse)(nil), "api.PutVespiaryEventsResponse")
}

func init() { proto.RegisterFile("vespiary.proto", fileDescriptor_efc1ff1bbf92a481) }

var fileDescriptor_efc1ff1bbf92a481 = []byte{
	// 857 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x56, 0x5b, 0x4f, 0xdb, 0x48,
	0x14, 0x5e, 0xc7, 0x21, 0x24, 0x27, 0x5c, 0x87, 0x5c, 0x1c, 0x83, 0x50, 0xd6, 0xab, 0xdd, 0x8d,
	0xf6, 0x81, 0x95, 0x52, 0xa9, 0xa2, 0x85, 0x07, 0x22, 0x02, 0x15, 0xa5, 0xa2, 0xc8, 0x50, 0x5e,
	0xfa, 0x64, 0x92, 0x51, 0xb1, 0x94, 0xd8, 0xa9, 0x67, 0x92, 0x88, 0xff, 0xd1, 0x3e, 0xf5, 0x57,
	0xf5, 0x1f, 0x55, 0x1e, 0x9f, 0xf1, 0x8d, 0x09, 0x4a, 0x79, 0xf3, 0x9c, 0xcb, 0x77, 0xce, 0xcc,
	0xf9, 0xe6, 0x1b, 0xc3, 0xc6, 0x8c, 0xb2, 0x89, 0xeb, 0x04, 0x8f, 0x07, 0x93, 0xc0, 0xe7, 0x3e,
	0xd1, 0x9d, 0x89, 0x6b, 0x7d, 0xd7, 0x60, 0xb5, 0x37, 0x18, 0xf8, 0x53, 0x8f, 0x93, 0x0d, 0x28,
	0x5c, 0xf4, 0x0d, 0xad, 0xad, 0x75, 0x2a, 0x76, 0xe1, 0xa2, 0x4f, 0x08, 0x14, 0xaf, 0x9c, 0x31,
	0x35, 0x0a, 0xc2, 0x22, 0xbe, 0xc9, 0x3e, 0xc0, 0x75, 0xe0, 0x7a, 0x03, 0x77, 0xe2, 0x8c, 0x98,
	0xa1, 0xb7, 0xf5, 0x4e, 0xc5, 0x4e, 0x59, 0x48, 0x07, 0x36, 0xfb, 0x74, 0xe6, 0x0e, 0xe8, 0x27,
	0x46, 0x03, 0xcf, 0x19, 0x53, 0x66, 0x14, 0x45, 0x50, 0xde, 0x4c, 0xf6, 0xa0, 0x72, 0x1a, 0x50,
	0x87, 0xd3, 0x61, 0x8f, 0x1b, 0x2b, 0x6d, 0xad, 0xa3, 0xdb, 0x89, 0xc1, 0x7a, 0x0d, 0x80, 0x6d,
	0xdd, 0x50, 0x4e, 0x3a, 0x50, 0xc6, 0x15, 0x33, 0xb4, 0xb6, 0xde, 0xa9, 0x76, 0xd7, 0x0e, 0x9c,
	0x89, 0x7b, 0x80, 0x46, 0x3b, 0xf6, 0x5a, 0x5d, 0xa8, 0x44, 0x85, 0xc2, 0xb4, 0xbf, 0x61, 0x35,
	0x5a, 0xc8, 0xac, 0xaa, 0xc8, 0x8a, 0x6c, 0xb6, 0xf4, 0x59, 0xdf, 0x34, 0x28, 0x45, 0xdf, 0xa4,
	0x06, 0x2b, 0x1f, 0xe7, 0x1e, 0x0d, 0xf0, 0x14, 0xa2, 0x05, 0x1e, 0x4c, 0xe1, 0xc9, 0xc1, 0xe8,
	0xa9, 0x83, 0x69, 0x40, 0xa9, 0x37, 0xe0, 0xee, 0x8c, 0x1a, 0xc5, 0xb6, 0xd6, 0x29, 0xdb, 0xb8,
	0x7a, 0x7e, 0x9b, 0xc4, 0x84, 0xf2, 0xb5, 0xc3, 0xd8, 0xdc, 0x0f, 0x86, 0x46, 0x49, 0xa0, 0xc5,
	0x6b, 0x8b, 0xc1, 0x4e, 0x14, 0x88, 0xfd, 0xd2, 0xaf, 0x53, 0xca, 0xf8, 0x82, 0x16, 0x55, 0xb3,
	0x4a, 0x5a, 0xd2, 0x33, 0x2d, 0xa5, 0x8b, 0x16, 0x73, 0x45, 0xff, 0x81, 0x5a, 0xb6, 0x28, 0x9b,
	0xf8, 0x1e, 0xa3, 0x79, 0x6e, 0x58, 0x47, 0xb0, 0xd3, 0xa7, 0x23, 0xba, 0x5c, 0x73, 0xb9, 0xf3,
	0x0b, 0x8b, 0x64, 0x93, 0x17, 0x14, 0xf9, 0x0f, 0xc8, 0x07, 0x97, 0x71, 0x9c, 0xd3, 0xb3, 0x35,
	0xac, 0x63, 0xd8, 0xc9, 0xc4, 0x22, 0xe4, 0x92, 0x14, 0x38, 0x84, 0xad, 0x77, 0x94, 0xbf, 0x64,
	0x2f, 0x87, 0xb0, 0x9d, 0xca, 0xc4, 0xaa, 0x7f, 0x49, 0x42, 0x89, 0xdc, 0x5c, 0x51, 0x74, 0x85,
	0x47, 0x78, 0xe6, 0x39, 0xf7, 0xa3, 0x17, 0x1d, 0x61, 0x03, 0x6a, 0xd9, 0xe4, 0xa8, 0xb2, 0x75,
	0x0c, 0xb5, 0xbe, 0xcb, 0x5e, 0x8a, 0xda, 0x84, 0x7a, 0x2e, 0x1b, 0x61, 0x29, 0xec, 0x9e, 0x3e,
	0x38, 0xde, 0x17, 0xb4, 0x4b, 0xba, 0xfc, 0x16, 0x3a, 0x69, 0x43, 0xf5, 0x8a, 0xce, 0x63, 0xea,
	0x45, 0xb7, 0x27, 0x6d, 0xb2, 0xf6, 0x61, 0x4f, 0x5d, 0x06, 0xdb, 0xe0, 0x92, 0x9d, 0xf2, 0xe2,
	0x63, 0x7d, 0xc9, 0x7e, 0x6d, 0xa1, 0x52, 0x15, 0x96, 0x51, 0x2a, 0x5d, 0xa9, 0x54, 0xd6, 0xbf,
	0x50, 0xcf, 0x55, 0x5d, 0xc0, 0xd7, 0x98, 0xd7, 0xb9, 0xf6, 0xf2, 0x71, 0xe1, 0x31, 0x67, 0xe3,
	0x70, 0x7f, 0xf5, 0x88, 0xc4, 0x52, 0xcd, 0x30, 0xdf, 0x3a, 0x81, 0x5a, 0xd6, 0x8c, 0xf5, 0x97,
	0x97, 0xc5, 0x6d, 0xd8, 0xbc, 0x79, 0x98, 0xf2, 0xa1, 0x3f, 0xf7, 0x24, 0x28, 0x81, 0xad, 0xc4,
	0x84, 0xf5, 0x4f, 0xa0, 0x71, 0x87, 0x8f, 0xc4, 0xd9, 0x8c, 0x7a, 0xbc, 0xc7, 0x79, 0xe0, 0xde,
	0x4f, 0x39, 0x25, 0x5b, 0xa0, 0x5f, 0xd2, 0x47, 0xdc, 0x43, 0xf8, 0x19, 0xce, 0xfc, 0xce, 0x19,
	0x4d, 0xa5, 0xe4, 0x44, 0x0b, 0xeb, 0x87, 0x06, 0x44, 0x42, 0xf4, 0xa6, 0x43, 0x97, 0x0b, 0x9c,
	0x50, 0x05, 0x6f, 0xdd, 0x31, 0x65, 0xdc, 0x19, 0x4f, 0x04, 0x88, 0x6e, 0x27, 0x86, 0x50, 0xa8,
	0x6e, 0xa9, 0xe7, 0x78, 0x1c, 0xb1, 0x70, 0x15, 0x8e, 0xf5, 0xd2, 0xf5, 0x24, 0x53, 0xc4, 0x37,
	0x39, 0x02, 0x88, 0xbb, 0x8a, 0xde, 0x96, 0x6a, 0x77, 0x57, 0xec, 0x5a, 0xdd, 0xb9, 0x9d, 0x0a,
	0xb7, 0xde, 0x43, 0xf3, 0x7a, 0xca, 0x33, 0x81, 0x72, 0x46, 0xff, 0x43, 0x49, 0xac, 0xe5, 0x49,
	0x36, 0x33, 0x98, 0xc9, 0x56, 0x6c, 0x0c, 0xb3, 0x76, 0xa1, 0x95, 0xc7, 0x8a, 0x27, 0xd3, 0xfd,
	0xb9, 0x02, 0x65, 0xe9, 0x22, 0xe7, 0xb0, 0x9e, 0xe1, 0x0f, 0x69, 0x09, 0x6c, 0x15, 0x93, 0x4d,
	0x53, 0xe5, 0xc2, 0x71, 0x9f, 0xc3, 0x7a, 0x86, 0x36, 0x88, 0xa3, 0xa2, 0x1c, 0xe2, 0x28, 0x59,
	0x46, 0x4e, 0x61, 0x2d, 0x4d, 0x27, 0x62, 0x88, 0x58, 0x05, 0xf1, 0xcc, 0x96, 0xc2, 0x93, 0x80,
	0xa4, 0x1f, 0x0a, 0x04, 0x51, 0x3c, 0x58, 0x66, 0x4b, 0xe1, 0x49, 0x40, 0xd2, 0x0f, 0x01, 0x82,
	0x28, 0x1e, 0x16, 0xb3, 0xa5, 0xf0, 0x20, 0xc8, 0x09, 0x54, 0x53, 0xca, 0x4f, 0x9a, 0x71, 0xcf,
	0xd9, 0x77, 0xc3, 0x34, 0x9e, 0x3a, 0x10, 0xe1, 0x2d, 0x54, 0x62, 0x0d, 0x27, 0x75, 0x11, 0x96,
	0x7f, 0x0d, 0xcc, 0x46, 0xde, 0x9c, 0x6c, 0x21, 0x2d, 0xc4, 0xb8, 0x05, 0x85, 0xb0, 0xe3, 0x16,
	0x54, 0xaa, 0x2d, 0x26, 0x9b, 0xd6, 0x5d, 0x39, 0x59, 0x85, 0x92, 0xcb, 0xc9, 0xaa, 0x64, 0x9a,
	0x7c, 0x86, 0x9a, 0x4a, 0x3f, 0x49, 0x3b, 0x1a, 0xc1, 0x62, 0x05, 0x37, 0xff, 0x7c, 0x26, 0x02,
	0x39, 0xdd, 0x83, 0xe2, 0x95, 0x3f, 0xa4, 0xe4, 0x0d, 0x94, 0xa5, 0x70, 0x90, 0x9a, 0x48, 0xcb,
	0x49, 0x8b, 0x59, 0xcf, 0x59, 0x51, 0x5d, 0xfe, 0xe8, 0x8e, 0xa0, 0x9e, 0xb9, 0x51, 0x36, 0x1d,
	0xf8, 0xc1, 0x90, 0x06, 0xe4, 0x06, 0xb6, 0x9f, 0x5c, 0x26, 0xb2, 0x27, 0x60, 0x16, 0x5c, 0x58,
	0x73, 0x5f, 0xe9, 0x65, 0x49, 0xb5, 0xfb, 0x92, 0xf8, 0xcf, 0x7d, 0xf5, 0x2b, 0x00, 0x00, 0xff,
	0xff, 0x25, 0x44, 0x6f, 0x75, 0xf9, 0x0a, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// VespiaryClient is the client API for Vespiary service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VespiaryClient interface {
	CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error)
	DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error)
	ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error)
	CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error)
	DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error)
	ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error)
	GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error)
	EnableDevice(ctx context.Context, in *EnableDeviceRequest, opts ...grpc.CallOption) (*EnableDeviceResponse, error)
	DisableDevice(ctx context.Context, in *DisableDeviceRequest, opts ...grpc.CallOption) (*DisableDeviceResponse, error)
	ChangeDevicePassword(ctx context.Context, in *ChangeDevicePasswordRequest, opts ...grpc.CallOption) (*ChangeDevicePasswordResponse, error)
}

type vespiaryClient struct {
	cc *grpc.ClientConn
}

func NewVespiaryClient(cc *grpc.ClientConn) VespiaryClient {
	return &vespiaryClient{cc}
}

func (c *vespiaryClient) CreateAccount(ctx context.Context, in *CreateAccountRequest, opts ...grpc.CallOption) (*CreateAccountResponse, error) {
	out := new(CreateAccountResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/CreateAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) DeleteAccount(ctx context.Context, in *DeleteAccountRequest, opts ...grpc.CallOption) (*DeleteAccountResponse, error) {
	out := new(DeleteAccountResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/DeleteAccount", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) ListAccounts(ctx context.Context, in *ListAccountsRequest, opts ...grpc.CallOption) (*ListAccountsResponse, error) {
	out := new(ListAccountsResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/ListAccounts", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) CreateDevice(ctx context.Context, in *CreateDeviceRequest, opts ...grpc.CallOption) (*CreateDeviceResponse, error) {
	out := new(CreateDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/CreateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) DeleteDevice(ctx context.Context, in *DeleteDeviceRequest, opts ...grpc.CallOption) (*DeleteDeviceResponse, error) {
	out := new(DeleteDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) ListDevices(ctx context.Context, in *ListDevicesRequest, opts ...grpc.CallOption) (*ListDevicesResponse, error) {
	out := new(ListDevicesResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/ListDevices", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) GetDevice(ctx context.Context, in *GetDeviceRequest, opts ...grpc.CallOption) (*GetDeviceResponse, error) {
	out := new(GetDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/GetDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) EnableDevice(ctx context.Context, in *EnableDeviceRequest, opts ...grpc.CallOption) (*EnableDeviceResponse, error) {
	out := new(EnableDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/EnableDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) DisableDevice(ctx context.Context, in *DisableDeviceRequest, opts ...grpc.CallOption) (*DisableDeviceResponse, error) {
	out := new(DisableDeviceResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/DisableDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vespiaryClient) ChangeDevicePassword(ctx context.Context, in *ChangeDevicePasswordRequest, opts ...grpc.CallOption) (*ChangeDevicePasswordResponse, error) {
	out := new(ChangeDevicePasswordResponse)
	err := c.cc.Invoke(ctx, "/api.Vespiary/ChangeDevicePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VespiaryServer is the server API for Vespiary service.
type VespiaryServer interface {
	CreateAccount(context.Context, *CreateAccountRequest) (*CreateAccountResponse, error)
	DeleteAccount(context.Context, *DeleteAccountRequest) (*DeleteAccountResponse, error)
	ListAccounts(context.Context, *ListAccountsRequest) (*ListAccountsResponse, error)
	CreateDevice(context.Context, *CreateDeviceRequest) (*CreateDeviceResponse, error)
	DeleteDevice(context.Context, *DeleteDeviceRequest) (*DeleteDeviceResponse, error)
	ListDevices(context.Context, *ListDevicesRequest) (*ListDevicesResponse, error)
	GetDevice(context.Context, *GetDeviceRequest) (*GetDeviceResponse, error)
	EnableDevice(context.Context, *EnableDeviceRequest) (*EnableDeviceResponse, error)
	DisableDevice(context.Context, *DisableDeviceRequest) (*DisableDeviceResponse, error)
	ChangeDevicePassword(context.Context, *ChangeDevicePasswordRequest) (*ChangeDevicePasswordResponse, error)
}

// UnimplementedVespiaryServer can be embedded to have forward compatible implementations.
type UnimplementedVespiaryServer struct {
}

func (*UnimplementedVespiaryServer) CreateAccount(ctx context.Context, req *CreateAccountRequest) (*CreateAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateAccount not implemented")
}
func (*UnimplementedVespiaryServer) DeleteAccount(ctx context.Context, req *DeleteAccountRequest) (*DeleteAccountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAccount not implemented")
}
func (*UnimplementedVespiaryServer) ListAccounts(ctx context.Context, req *ListAccountsRequest) (*ListAccountsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListAccounts not implemented")
}
func (*UnimplementedVespiaryServer) CreateDevice(ctx context.Context, req *CreateDeviceRequest) (*CreateDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevice not implemented")
}
func (*UnimplementedVespiaryServer) DeleteDevice(ctx context.Context, req *DeleteDeviceRequest) (*DeleteDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (*UnimplementedVespiaryServer) ListDevices(ctx context.Context, req *ListDevicesRequest) (*ListDevicesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevices not implemented")
}
func (*UnimplementedVespiaryServer) GetDevice(ctx context.Context, req *GetDeviceRequest) (*GetDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDevice not implemented")
}
func (*UnimplementedVespiaryServer) EnableDevice(ctx context.Context, req *EnableDeviceRequest) (*EnableDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnableDevice not implemented")
}
func (*UnimplementedVespiaryServer) DisableDevice(ctx context.Context, req *DisableDeviceRequest) (*DisableDeviceResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DisableDevice not implemented")
}
func (*UnimplementedVespiaryServer) ChangeDevicePassword(ctx context.Context, req *ChangeDevicePasswordRequest) (*ChangeDevicePasswordResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangeDevicePassword not implemented")
}

func RegisterVespiaryServer(s *grpc.Server, srv VespiaryServer) {
	s.RegisterService(&_Vespiary_serviceDesc, srv)
}

func _Vespiary_CreateAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).CreateAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/CreateAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).CreateAccount(ctx, req.(*CreateAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_DeleteAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).DeleteAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/DeleteAccount",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).DeleteAccount(ctx, req.(*DeleteAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_ListAccounts_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAccountsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).ListAccounts(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/ListAccounts",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).ListAccounts(ctx, req.(*ListAccountsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/CreateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).CreateDevice(ctx, req.(*CreateDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).DeleteDevice(ctx, req.(*DeleteDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_ListDevices_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDevicesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).ListDevices(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/ListDevices",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).ListDevices(ctx, req.(*ListDevicesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_GetDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).GetDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/GetDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).GetDevice(ctx, req.(*GetDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_EnableDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnableDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).EnableDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/EnableDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).EnableDevice(ctx, req.(*EnableDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_DisableDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DisableDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).DisableDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/DisableDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).DisableDevice(ctx, req.(*DisableDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Vespiary_ChangeDevicePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeDevicePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryServer).ChangeDevicePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Vespiary/ChangeDevicePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryServer).ChangeDevicePassword(ctx, req.(*ChangeDevicePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Vespiary_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Vespiary",
	HandlerType: (*VespiaryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateAccount",
			Handler:    _Vespiary_CreateAccount_Handler,
		},
		{
			MethodName: "DeleteAccount",
			Handler:    _Vespiary_DeleteAccount_Handler,
		},
		{
			MethodName: "ListAccounts",
			Handler:    _Vespiary_ListAccounts_Handler,
		},
		{
			MethodName: "CreateDevice",
			Handler:    _Vespiary_CreateDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _Vespiary_DeleteDevice_Handler,
		},
		{
			MethodName: "ListDevices",
			Handler:    _Vespiary_ListDevices_Handler,
		},
		{
			MethodName: "GetDevice",
			Handler:    _Vespiary_GetDevice_Handler,
		},
		{
			MethodName: "EnableDevice",
			Handler:    _Vespiary_EnableDevice_Handler,
		},
		{
			MethodName: "DisableDevice",
			Handler:    _Vespiary_DisableDevice_Handler,
		},
		{
			MethodName: "ChangeDevicePassword",
			Handler:    _Vespiary_ChangeDevicePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vespiary.proto",
}

// NodeClient is the client API for Node service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type NodeClient interface {
	Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error)
}

type nodeClient struct {
	cc *grpc.ClientConn
}

func NewNodeClient(cc *grpc.ClientConn) NodeClient {
	return &nodeClient{cc}
}

func (c *nodeClient) Shutdown(ctx context.Context, in *ShutdownRequest, opts ...grpc.CallOption) (*ShutdownResponse, error) {
	out := new(ShutdownResponse)
	err := c.cc.Invoke(ctx, "/api.Node/Shutdown", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// NodeServer is the server API for Node service.
type NodeServer interface {
	Shutdown(context.Context, *ShutdownRequest) (*ShutdownResponse, error)
}

// UnimplementedNodeServer can be embedded to have forward compatible implementations.
type UnimplementedNodeServer struct {
}

func (*UnimplementedNodeServer) Shutdown(ctx context.Context, req *ShutdownRequest) (*ShutdownResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Shutdown not implemented")
}

func RegisterNodeServer(s *grpc.Server, srv NodeServer) {
	s.RegisterService(&_Node_serviceDesc, srv)
}

func _Node_Shutdown_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShutdownRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(NodeServer).Shutdown(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Node/Shutdown",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(NodeServer).Shutdown(ctx, req.(*ShutdownRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Node_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.Node",
	HandlerType: (*NodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Shutdown",
			Handler:    _Node_Shutdown_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vespiary.proto",
}

// VespiaryAuditRecorderClient is the client API for VespiaryAuditRecorder service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type VespiaryAuditRecorderClient interface {
	PutVespiaryEvents(ctx context.Context, in *PutVespiaryEventRequest, opts ...grpc.CallOption) (*PutVespiaryEventsResponse, error)
}

type vespiaryAuditRecorderClient struct {
	cc *grpc.ClientConn
}

func NewVespiaryAuditRecorderClient(cc *grpc.ClientConn) VespiaryAuditRecorderClient {
	return &vespiaryAuditRecorderClient{cc}
}

func (c *vespiaryAuditRecorderClient) PutVespiaryEvents(ctx context.Context, in *PutVespiaryEventRequest, opts ...grpc.CallOption) (*PutVespiaryEventsResponse, error) {
	out := new(PutVespiaryEventsResponse)
	err := c.cc.Invoke(ctx, "/api.VespiaryAuditRecorder/PutVespiaryEvents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VespiaryAuditRecorderServer is the server API for VespiaryAuditRecorder service.
type VespiaryAuditRecorderServer interface {
	PutVespiaryEvents(context.Context, *PutVespiaryEventRequest) (*PutVespiaryEventsResponse, error)
}

// UnimplementedVespiaryAuditRecorderServer can be embedded to have forward compatible implementations.
type UnimplementedVespiaryAuditRecorderServer struct {
}

func (*UnimplementedVespiaryAuditRecorderServer) PutVespiaryEvents(ctx context.Context, req *PutVespiaryEventRequest) (*PutVespiaryEventsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PutVespiaryEvents not implemented")
}

func RegisterVespiaryAuditRecorderServer(s *grpc.Server, srv VespiaryAuditRecorderServer) {
	s.RegisterService(&_VespiaryAuditRecorder_serviceDesc, srv)
}

func _VespiaryAuditRecorder_PutVespiaryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutVespiaryEventRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VespiaryAuditRecorderServer).PutVespiaryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.VespiaryAuditRecorder/PutVespiaryEvents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VespiaryAuditRecorderServer).PutVespiaryEvents(ctx, req.(*PutVespiaryEventRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _VespiaryAuditRecorder_serviceDesc = grpc.ServiceDesc{
	ServiceName: "api.VespiaryAuditRecorder",
	HandlerType: (*VespiaryAuditRecorderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutVespiaryEvents",
			Handler:    _VespiaryAuditRecorder_PutVespiaryEvents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vespiary.proto",
}
