// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package fsm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateTransitionSet struct {
	Events               []*StateTransition `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StateTransitionSet) Reset()         { *m = StateTransitionSet{} }
func (m *StateTransitionSet) String() string { return proto.CompactTextString(m) }
func (*StateTransitionSet) ProtoMessage()    {}
func (*StateTransitionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *StateTransitionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransitionSet.Unmarshal(m, b)
}
func (m *StateTransitionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransitionSet.Marshal(b, m, deterministic)
}
func (m *StateTransitionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransitionSet.Merge(m, src)
}
func (m *StateTransitionSet) XXX_Size() int {
	return xxx_messageInfo_StateTransitionSet.Size(m)
}
func (m *StateTransitionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransitionSet.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransitionSet proto.InternalMessageInfo

func (m *StateTransitionSet) GetEvents() []*StateTransition {
	if m != nil {
		return m.Events
	}
	return nil
}

type AccountCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Principals           []string `protobuf:"bytes,3,rep,name=Principals,proto3" json:"Principals,omitempty"`
	DeviceUsernames      []string `protobuf:"bytes,4,rep,name=DeviceUsernames,proto3" json:"DeviceUsernames,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCreated) Reset()         { *m = AccountCreated{} }
func (m *AccountCreated) String() string { return proto.CompactTextString(m) }
func (*AccountCreated) ProtoMessage()    {}
func (*AccountCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *AccountCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreated.Unmarshal(m, b)
}
func (m *AccountCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreated.Marshal(b, m, deterministic)
}
func (m *AccountCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreated.Merge(m, src)
}
func (m *AccountCreated) XXX_Size() int {
	return xxx_messageInfo_AccountCreated.Size(m)
}
func (m *AccountCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreated.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreated proto.InternalMessageInfo

func (m *AccountCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountCreated) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *AccountCreated) GetDeviceUsernames() []string {
	if m != nil {
		return m.DeviceUsernames
	}
	return nil
}

func (m *AccountCreated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type AccountDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeleted) Reset()         { *m = AccountDeleted{} }
func (m *AccountDeleted) String() string { return proto.CompactTextString(m) }
func (*AccountDeleted) ProtoMessage()    {}
func (*AccountDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *AccountDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeleted.Unmarshal(m, b)
}
func (m *AccountDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeleted.Marshal(b, m, deterministic)
}
func (m *AccountDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeleted.Merge(m, src)
}
func (m *AccountDeleted) XXX_Size() int {
	return xxx_messageInfo_AccountDeleted.Size(m)
}
func (m *AccountDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeleted proto.InternalMessageInfo

func (m *AccountDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type AccountDeviceUsernameAdded struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceUsername       string   `protobuf:"bytes,2,opt,name=DeviceUsername,proto3" json:"DeviceUsername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeviceUsernameAdded) Reset()         { *m = AccountDeviceUsernameAdded{} }
func (m *AccountDeviceUsernameAdded) String() string { return proto.CompactTextString(m) }
func (*AccountDeviceUsernameAdded) ProtoMessage()    {}
func (*AccountDeviceUsernameAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *AccountDeviceUsernameAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeviceUsernameAdded.Unmarshal(m, b)
}
func (m *AccountDeviceUsernameAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeviceUsernameAdded.Marshal(b, m, deterministic)
}
func (m *AccountDeviceUsernameAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeviceUsernameAdded.Merge(m, src)
}
func (m *AccountDeviceUsernameAdded) XXX_Size() int {
	return xxx_messageInfo_AccountDeviceUsernameAdded.Size(m)
}
func (m *AccountDeviceUsernameAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeviceUsernameAdded.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeviceUsernameAdded proto.InternalMessageInfo

func (m *AccountDeviceUsernameAdded) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountDeviceUsernameAdded) GetDeviceUsername() string {
	if m != nil {
		return m.DeviceUsername
	}
	return ""
}

type AccountDeviceUsernameRemoved struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceUsername       string   `protobuf:"bytes,2,opt,name=DeviceUsername,proto3" json:"DeviceUsername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeviceUsernameRemoved) Reset()         { *m = AccountDeviceUsernameRemoved{} }
func (m *AccountDeviceUsernameRemoved) String() string { return proto.CompactTextString(m) }
func (*AccountDeviceUsernameRemoved) ProtoMessage()    {}
func (*AccountDeviceUsernameRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *AccountDeviceUsernameRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeviceUsernameRemoved.Unmarshal(m, b)
}
func (m *AccountDeviceUsernameRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeviceUsernameRemoved.Marshal(b, m, deterministic)
}
func (m *AccountDeviceUsernameRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeviceUsernameRemoved.Merge(m, src)
}
func (m *AccountDeviceUsernameRemoved) XXX_Size() int {
	return xxx_messageInfo_AccountDeviceUsernameRemoved.Size(m)
}
func (m *AccountDeviceUsernameRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeviceUsernameRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeviceUsernameRemoved proto.InternalMessageInfo

func (m *AccountDeviceUsernameRemoved) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountDeviceUsernameRemoved) GetDeviceUsername() string {
	if m != nil {
		return m.DeviceUsername
	}
	return ""
}

type DeviceCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=Active,proto3" json:"Active,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceCreated) Reset()         { *m = DeviceCreated{} }
func (m *DeviceCreated) String() string { return proto.CompactTextString(m) }
func (*DeviceCreated) ProtoMessage()    {}
func (*DeviceCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *DeviceCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCreated.Unmarshal(m, b)
}
func (m *DeviceCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCreated.Marshal(b, m, deterministic)
}
func (m *DeviceCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCreated.Merge(m, src)
}
func (m *DeviceCreated) XXX_Size() int {
	return xxx_messageInfo_DeviceCreated.Size(m)
}
func (m *DeviceCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCreated.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCreated proto.InternalMessageInfo

func (m *DeviceCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceCreated) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeviceCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceCreated) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *DeviceCreated) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DeviceCreated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type DeviceDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDeleted) Reset()         { *m = DeviceDeleted{} }
func (m *DeviceDeleted) String() string { return proto.CompactTextString(m) }
func (*DeviceDeleted) ProtoMessage()    {}
func (*DeviceDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *DeviceDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDeleted.Unmarshal(m, b)
}
func (m *DeviceDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDeleted.Marshal(b, m, deterministic)
}
func (m *DeviceDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDeleted.Merge(m, src)
}
func (m *DeviceDeleted) XXX_Size() int {
	return xxx_messageInfo_DeviceDeleted.Size(m)
}
func (m *DeviceDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDeleted proto.InternalMessageInfo

func (m *DeviceDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceDeleted) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeviceEnabled struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceEnabled) Reset()         { *m = DeviceEnabled{} }
func (m *DeviceEnabled) String() string { return proto.CompactTextString(m) }
func (*DeviceEnabled) ProtoMessage()    {}
func (*DeviceEnabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *DeviceEnabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEnabled.Unmarshal(m, b)
}
func (m *DeviceEnabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEnabled.Marshal(b, m, deterministic)
}
func (m *DeviceEnabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEnabled.Merge(m, src)
}
func (m *DeviceEnabled) XXX_Size() int {
	return xxx_messageInfo_DeviceEnabled.Size(m)
}
func (m *DeviceEnabled) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEnabled.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEnabled proto.InternalMessageInfo

func (m *DeviceEnabled) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceEnabled) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeviceDisabled struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDisabled) Reset()         { *m = DeviceDisabled{} }
func (m *DeviceDisabled) String() string { return proto.CompactTextString(m) }
func (*DeviceDisabled) ProtoMessage()    {}
func (*DeviceDisabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *DeviceDisabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDisabled.Unmarshal(m, b)
}
func (m *DeviceDisabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDisabled.Marshal(b, m, deterministic)
}
func (m *DeviceDisabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDisabled.Merge(m, src)
}
func (m *DeviceDisabled) XXX_Size() int {
	return xxx_messageInfo_DeviceDisabled.Size(m)
}
func (m *DeviceDisabled) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDisabled.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDisabled proto.InternalMessageInfo

func (m *DeviceDisabled) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceDisabled) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DevicePasswordChanged struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevicePasswordChanged) Reset()         { *m = DevicePasswordChanged{} }
func (m *DevicePasswordChanged) String() string { return proto.CompactTextString(m) }
func (*DevicePasswordChanged) ProtoMessage()    {}
func (*DevicePasswordChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *DevicePasswordChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicePasswordChanged.Unmarshal(m, b)
}
func (m *DevicePasswordChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicePasswordChanged.Marshal(b, m, deterministic)
}
func (m *DevicePasswordChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicePasswordChanged.Merge(m, src)
}
func (m *DevicePasswordChanged) XXX_Size() int {
	return xxx_messageInfo_DevicePasswordChanged.Size(m)
}
func (m *DevicePasswordChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicePasswordChanged.DiscardUnknown(m)
}

var xxx_messageInfo_DevicePasswordChanged proto.InternalMessageInfo

func (m *DevicePasswordChanged) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DevicePasswordChanged) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DevicePasswordChanged) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type ApplicationCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	AccountID            string   `protobuf:"bytes,2,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt            int64    `protobuf:"varint,4,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationCreated) Reset()         { *m = ApplicationCreated{} }
func (m *ApplicationCreated) String() string { return proto.CompactTextString(m) }
func (*ApplicationCreated) ProtoMessage()    {}
func (*ApplicationCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *ApplicationCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationCreated.Unmarshal(m, b)
}
func (m *ApplicationCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationCreated.Marshal(b, m, deterministic)
}
func (m *ApplicationCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationCreated.Merge(m, src)
}
func (m *ApplicationCreated) XXX_Size() int {
	return xxx_messageInfo_ApplicationCreated.Size(m)
}
func (m *ApplicationCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationCreated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationCreated proto.InternalMessageInfo

func (m *ApplicationCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ApplicationCreated) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *ApplicationCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationCreated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type ApplicationDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationDeleted) Reset()         { *m = ApplicationDeleted{} }
func (m *ApplicationDeleted) String() string { return proto.CompactTextString(m) }
func (*ApplicationDeleted) ProtoMessage()    {}
func (*ApplicationDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *ApplicationDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationDeleted.Unmarshal(m, b)
}
func (m *ApplicationDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationDeleted.Marshal(b, m, deterministic)
}
func (m *ApplicationDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationDeleted.Merge(m, src)
}
func (m *ApplicationDeleted) XXX_Size() int {
	return xxx_messageInfo_ApplicationDeleted.Size(m)
}
func (m *ApplicationDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationDeleted proto.InternalMessageInfo

func (m *ApplicationDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type ApplicationProfileCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	ApplicationID        string   `protobuf:"bytes,2,opt,name=ApplicationID,proto3" json:"ApplicationID,omitempty"`
	AccountID            string   `protobuf:"bytes,3,opt,name=AccountID,proto3" json:"AccountID,omitempty"`
	Name                 string   `protobuf:"bytes,4,opt,name=Name,proto3" json:"Name,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	Enabled              bool     `protobuf:"varint,6,opt,name=Enabled,proto3" json:"Enabled,omitempty"`
	PasswordFingerprint  []byte   `protobuf:"bytes,7,opt,name=PasswordFingerprint,proto3" json:"PasswordFingerprint,omitempty"`
	PasswordSalt         []byte   `protobuf:"bytes,8,opt,name=PasswordSalt,proto3" json:"PasswordSalt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationProfileCreated) Reset()         { *m = ApplicationProfileCreated{} }
func (m *ApplicationProfileCreated) String() string { return proto.CompactTextString(m) }
func (*ApplicationProfileCreated) ProtoMessage()    {}
func (*ApplicationProfileCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{12}
}

func (m *ApplicationProfileCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationProfileCreated.Unmarshal(m, b)
}
func (m *ApplicationProfileCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationProfileCreated.Marshal(b, m, deterministic)
}
func (m *ApplicationProfileCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationProfileCreated.Merge(m, src)
}
func (m *ApplicationProfileCreated) XXX_Size() int {
	return xxx_messageInfo_ApplicationProfileCreated.Size(m)
}
func (m *ApplicationProfileCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationProfileCreated.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationProfileCreated proto.InternalMessageInfo

func (m *ApplicationProfileCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *ApplicationProfileCreated) GetApplicationID() string {
	if m != nil {
		return m.ApplicationID
	}
	return ""
}

func (m *ApplicationProfileCreated) GetAccountID() string {
	if m != nil {
		return m.AccountID
	}
	return ""
}

func (m *ApplicationProfileCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ApplicationProfileCreated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

func (m *ApplicationProfileCreated) GetEnabled() bool {
	if m != nil {
		return m.Enabled
	}
	return false
}

func (m *ApplicationProfileCreated) GetPasswordFingerprint() []byte {
	if m != nil {
		return m.PasswordFingerprint
	}
	return nil
}

func (m *ApplicationProfileCreated) GetPasswordSalt() []byte {
	if m != nil {
		return m.PasswordSalt
	}
	return nil
}

type ApplicationProfileDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ApplicationProfileDeleted) Reset()         { *m = ApplicationProfileDeleted{} }
func (m *ApplicationProfileDeleted) String() string { return proto.CompactTextString(m) }
func (*ApplicationProfileDeleted) ProtoMessage()    {}
func (*ApplicationProfileDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{13}
}

func (m *ApplicationProfileDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ApplicationProfileDeleted.Unmarshal(m, b)
}
func (m *ApplicationProfileDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ApplicationProfileDeleted.Marshal(b, m, deterministic)
}
func (m *ApplicationProfileDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ApplicationProfileDeleted.Merge(m, src)
}
func (m *ApplicationProfileDeleted) XXX_Size() int {
	return xxx_messageInfo_ApplicationProfileDeleted.Size(m)
}
func (m *ApplicationProfileDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_ApplicationProfileDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_ApplicationProfileDeleted proto.InternalMessageInfo

func (m *ApplicationProfileDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type StateTransition struct {
	// Types that are valid to be assigned to Event:
	//	*StateTransition_DeviceCreated
	//	*StateTransition_DeviceDeleted
	//	*StateTransition_DeviceEnabled
	//	*StateTransition_DeviceDisabled
	//	*StateTransition_DevicePasswordChanged
	//	*StateTransition_AccountCreated
	//	*StateTransition_AccountDeleted
	//	*StateTransition_AccountDeviceUsernameAdded
	//	*StateTransition_AccountDeviceUsernameRemoved
	//	*StateTransition_ApplicationCreated
	//	*StateTransition_ApplicationDeleted
	//	*StateTransition_ApplicationProfileCreated
	//	*StateTransition_ApplicationProfileDeleted
	Event                isStateTransition_Event `protobuf_oneof:"Event"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StateTransition) Reset()         { *m = StateTransition{} }
func (m *StateTransition) String() string { return proto.CompactTextString(m) }
func (*StateTransition) ProtoMessage()    {}
func (*StateTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{14}
}

func (m *StateTransition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransition.Unmarshal(m, b)
}
func (m *StateTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransition.Marshal(b, m, deterministic)
}
func (m *StateTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransition.Merge(m, src)
}
func (m *StateTransition) XXX_Size() int {
	return xxx_messageInfo_StateTransition.Size(m)
}
func (m *StateTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransition.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransition proto.InternalMessageInfo

type isStateTransition_Event interface {
	isStateTransition_Event()
}

type StateTransition_DeviceCreated struct {
	DeviceCreated *DeviceCreated `protobuf:"bytes,2,opt,name=DeviceCreated,proto3,oneof"`
}

type StateTransition_DeviceDeleted struct {
	DeviceDeleted *DeviceDeleted `protobuf:"bytes,3,opt,name=DeviceDeleted,proto3,oneof"`
}

type StateTransition_DeviceEnabled struct {
	DeviceEnabled *DeviceEnabled `protobuf:"bytes,4,opt,name=DeviceEnabled,proto3,oneof"`
}

type StateTransition_DeviceDisabled struct {
	DeviceDisabled *DeviceDisabled `protobuf:"bytes,5,opt,name=DeviceDisabled,proto3,oneof"`
}

type StateTransition_DevicePasswordChanged struct {
	DevicePasswordChanged *DevicePasswordChanged `protobuf:"bytes,6,opt,name=DevicePasswordChanged,proto3,oneof"`
}

type StateTransition_AccountCreated struct {
	AccountCreated *AccountCreated `protobuf:"bytes,7,opt,name=AccountCreated,proto3,oneof"`
}

type StateTransition_AccountDeleted struct {
	AccountDeleted *AccountDeleted `protobuf:"bytes,8,opt,name=AccountDeleted,proto3,oneof"`
}

type StateTransition_AccountDeviceUsernameAdded struct {
	AccountDeviceUsernameAdded *AccountDeviceUsernameAdded `protobuf:"bytes,9,opt,name=AccountDeviceUsernameAdded,proto3,oneof"`
}

type StateTransition_AccountDeviceUsernameRemoved struct {
	AccountDeviceUsernameRemoved *AccountDeviceUsernameRemoved `protobuf:"bytes,10,opt,name=AccountDeviceUsernameRemoved,proto3,oneof"`
}

type StateTransition_ApplicationCreated struct {
	ApplicationCreated *ApplicationCreated `protobuf:"bytes,11,opt,name=ApplicationCreated,proto3,oneof"`
}

type StateTransition_ApplicationDeleted struct {
	ApplicationDeleted *ApplicationDeleted `protobuf:"bytes,12,opt,name=ApplicationDeleted,proto3,oneof"`
}

type StateTransition_ApplicationProfileCreated struct {
	ApplicationProfileCreated *ApplicationProfileCreated `protobuf:"bytes,13,opt,name=ApplicationProfileCreated,proto3,oneof"`
}

type StateTransition_ApplicationProfileDeleted struct {
	ApplicationProfileDeleted *ApplicationProfileDeleted `protobuf:"bytes,14,opt,name=ApplicationProfileDeleted,proto3,oneof"`
}

func (*StateTransition_DeviceCreated) isStateTransition_Event() {}

func (*StateTransition_DeviceDeleted) isStateTransition_Event() {}

func (*StateTransition_DeviceEnabled) isStateTransition_Event() {}

func (*StateTransition_DeviceDisabled) isStateTransition_Event() {}

func (*StateTransition_DevicePasswordChanged) isStateTransition_Event() {}

func (*StateTransition_AccountCreated) isStateTransition_Event() {}

func (*StateTransition_AccountDeleted) isStateTransition_Event() {}

func (*StateTransition_AccountDeviceUsernameAdded) isStateTransition_Event() {}

func (*StateTransition_AccountDeviceUsernameRemoved) isStateTransition_Event() {}

func (*StateTransition_ApplicationCreated) isStateTransition_Event() {}

func (*StateTransition_ApplicationDeleted) isStateTransition_Event() {}

func (*StateTransition_ApplicationProfileCreated) isStateTransition_Event() {}

func (*StateTransition_ApplicationProfileDeleted) isStateTransition_Event() {}

func (m *StateTransition) GetEvent() isStateTransition_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StateTransition) GetDeviceCreated() *DeviceCreated {
	if x, ok := m.GetEvent().(*StateTransition_DeviceCreated); ok {
		return x.DeviceCreated
	}
	return nil
}

func (m *StateTransition) GetDeviceDeleted() *DeviceDeleted {
	if x, ok := m.GetEvent().(*StateTransition_DeviceDeleted); ok {
		return x.DeviceDeleted
	}
	return nil
}

func (m *StateTransition) GetDeviceEnabled() *DeviceEnabled {
	if x, ok := m.GetEvent().(*StateTransition_DeviceEnabled); ok {
		return x.DeviceEnabled
	}
	return nil
}

func (m *StateTransition) GetDeviceDisabled() *DeviceDisabled {
	if x, ok := m.GetEvent().(*StateTransition_DeviceDisabled); ok {
		return x.DeviceDisabled
	}
	return nil
}

func (m *StateTransition) GetDevicePasswordChanged() *DevicePasswordChanged {
	if x, ok := m.GetEvent().(*StateTransition_DevicePasswordChanged); ok {
		return x.DevicePasswordChanged
	}
	return nil
}

func (m *StateTransition) GetAccountCreated() *AccountCreated {
	if x, ok := m.GetEvent().(*StateTransition_AccountCreated); ok {
		return x.AccountCreated
	}
	return nil
}

func (m *StateTransition) GetAccountDeleted() *AccountDeleted {
	if x, ok := m.GetEvent().(*StateTransition_AccountDeleted); ok {
		return x.AccountDeleted
	}
	return nil
}

func (m *StateTransition) GetAccountDeviceUsernameAdded() *AccountDeviceUsernameAdded {
	if x, ok := m.GetEvent().(*StateTransition_AccountDeviceUsernameAdded); ok {
		return x.AccountDeviceUsernameAdded
	}
	return nil
}

func (m *StateTransition) GetAccountDeviceUsernameRemoved() *AccountDeviceUsernameRemoved {
	if x, ok := m.GetEvent().(*StateTransition_AccountDeviceUsernameRemoved); ok {
		return x.AccountDeviceUsernameRemoved
	}
	return nil
}

func (m *StateTransition) GetApplicationCreated() *ApplicationCreated {
	if x, ok := m.GetEvent().(*StateTransition_ApplicationCreated); ok {
		return x.ApplicationCreated
	}
	return nil
}

func (m *StateTransition) GetApplicationDeleted() *ApplicationDeleted {
	if x, ok := m.GetEvent().(*StateTransition_ApplicationDeleted); ok {
		return x.ApplicationDeleted
	}
	return nil
}

func (m *StateTransition) GetApplicationProfileCreated() *ApplicationProfileCreated {
	if x, ok := m.GetEvent().(*StateTransition_ApplicationProfileCreated); ok {
		return x.ApplicationProfileCreated
	}
	return nil
}

func (m *StateTransition) GetApplicationProfileDeleted() *ApplicationProfileDeleted {
	if x, ok := m.GetEvent().(*StateTransition_ApplicationProfileDeleted); ok {
		return x.ApplicationProfileDeleted
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StateTransition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StateTransition_DeviceCreated)(nil),
		(*StateTransition_DeviceDeleted)(nil),
		(*StateTransition_DeviceEnabled)(nil),
		(*StateTransition_DeviceDisabled)(nil),
		(*StateTransition_DevicePasswordChanged)(nil),
		(*StateTransition_AccountCreated)(nil),
		(*StateTransition_AccountDeleted)(nil),
		(*StateTransition_AccountDeviceUsernameAdded)(nil),
		(*StateTransition_AccountDeviceUsernameRemoved)(nil),
		(*StateTransition_ApplicationCreated)(nil),
		(*StateTransition_ApplicationDeleted)(nil),
		(*StateTransition_ApplicationProfileCreated)(nil),
		(*StateTransition_ApplicationProfileDeleted)(nil),
	}
}

func init() {
	proto.RegisterType((*StateTransitionSet)(nil), "fsm.StateTransitionSet")
	proto.RegisterType((*AccountCreated)(nil), "fsm.AccountCreated")
	proto.RegisterType((*AccountDeleted)(nil), "fsm.AccountDeleted")
	proto.RegisterType((*AccountDeviceUsernameAdded)(nil), "fsm.AccountDeviceUsernameAdded")
	proto.RegisterType((*AccountDeviceUsernameRemoved)(nil), "fsm.AccountDeviceUsernameRemoved")
	proto.RegisterType((*DeviceCreated)(nil), "fsm.DeviceCreated")
	proto.RegisterType((*DeviceDeleted)(nil), "fsm.DeviceDeleted")
	proto.RegisterType((*DeviceEnabled)(nil), "fsm.DeviceEnabled")
	proto.RegisterType((*DeviceDisabled)(nil), "fsm.DeviceDisabled")
	proto.RegisterType((*DevicePasswordChanged)(nil), "fsm.DevicePasswordChanged")
	proto.RegisterType((*ApplicationCreated)(nil), "fsm.ApplicationCreated")
	proto.RegisterType((*ApplicationDeleted)(nil), "fsm.ApplicationDeleted")
	proto.RegisterType((*ApplicationProfileCreated)(nil), "fsm.ApplicationProfileCreated")
	proto.RegisterType((*ApplicationProfileDeleted)(nil), "fsm.ApplicationProfileDeleted")
	proto.RegisterType((*StateTransition)(nil), "fsm.StateTransition")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 697 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x56, 0xdf, 0x4f, 0xdb, 0x3e,
	0x10, 0x4f, 0x9a, 0x52, 0xda, 0x2b, 0x14, 0xc9, 0xf0, 0xfd, 0xce, 0x43, 0x88, 0x65, 0x11, 0x9a,
	0x22, 0x6d, 0x42, 0x53, 0xa7, 0xed, 0x01, 0x89, 0x87, 0x42, 0x99, 0xd2, 0x97, 0x0d, 0x19, 0x36,
	0x69, 0x2f, 0x48, 0xa6, 0x35, 0x2c, 0x52, 0x9b, 0x54, 0x89, 0x57, 0xb4, 0xc7, 0xfd, 0x09, 0x7b,
	0xde, 0xfe, 0xd8, 0x09, 0xd7, 0x69, 0x62, 0x63, 0x47, 0x4c, 0x7b, 0x8b, 0xef, 0xc7, 0xc7, 0x77,
	0x9f, 0xf3, 0xdd, 0x05, 0xba, 0xfc, 0xfb, 0x9c, 0xe5, 0x87, 0xf3, 0x2c, 0xe5, 0x29, 0xf2, 0x6e,
	0xf2, 0x59, 0x70, 0x02, 0xe8, 0x82, 0x53, 0xce, 0x2e, 0x33, 0x9a, 0xe4, 0x31, 0x8f, 0xd3, 0xe4,
	0x82, 0x71, 0xf4, 0x0a, 0x5a, 0x6c, 0xc1, 0x12, 0x9e, 0x63, 0xd7, 0xf7, 0xc2, 0x6e, 0x7f, 0xe7,
	0xf0, 0x26, 0x9f, 0x1d, 0x6a, 0x86, 0x44, 0xda, 0x04, 0xbf, 0x5d, 0xe8, 0x0d, 0xc6, 0xe3, 0xf4,
	0x5b, 0xc2, 0x4f, 0x33, 0x46, 0x39, 0x9b, 0xa0, 0x1e, 0x34, 0x46, 0x43, 0xec, 0xfa, 0x6e, 0xd8,
	0x21, 0x8d, 0xd1, 0x10, 0x21, 0x68, 0x7e, 0xa0, 0x33, 0x86, 0x1b, 0x42, 0x22, 0xbe, 0xd1, 0x3e,
	0xc0, 0x79, 0x16, 0x27, 0xe3, 0x78, 0x4e, 0xa7, 0x39, 0xf6, 0x7c, 0x2f, 0xec, 0x90, 0x8a, 0x04,
	0x85, 0xb0, 0x35, 0x64, 0x8b, 0x78, 0xcc, 0x3e, 0xe5, 0x2c, 0x4b, 0xe8, 0x8c, 0xe5, 0xb8, 0x29,
	0x8c, 0x74, 0x31, 0xda, 0x83, 0x8e, 0xbc, 0x78, 0xc0, 0xf1, 0x9a, 0xef, 0x86, 0x1e, 0x29, 0x05,
	0x81, 0xbf, 0x8a, 0x6e, 0xc8, 0xa6, 0xcc, 0x10, 0x5d, 0x70, 0x09, 0xbb, 0x2b, 0x8b, 0x2a, 0xf2,
	0x60, 0x32, 0x31, 0xe4, 0xf2, 0x02, 0x7a, 0xaa, 0x99, 0xcc, 0x4a, 0x93, 0x06, 0x9f, 0x61, 0xcf,
	0x88, 0x4a, 0xd8, 0x2c, 0x5d, 0xfc, 0x03, 0xee, 0x2f, 0x17, 0x36, 0x97, 0x22, 0x1b, 0xdb, 0x3b,
	0xb0, 0xf6, 0xf1, 0x2e, 0x61, 0x99, 0x04, 0x58, 0x1e, 0x56, 0x35, 0xf0, 0x2a, 0x35, 0xf8, 0x1f,
	0x5a, 0x83, 0x31, 0x8f, 0x17, 0x0c, 0x37, 0x7d, 0x37, 0x6c, 0x13, 0x79, 0x42, 0xbb, 0xd0, 0x3e,
	0xa7, 0x79, 0x7e, 0x97, 0x66, 0x13, 0x41, 0x68, 0x87, 0xac, 0xce, 0x2a, 0xdb, 0x2d, 0x9d, 0xed,
	0xb7, 0x45, 0x70, 0x16, 0xb2, 0xcd, 0xc1, 0x95, 0x6e, 0x67, 0x09, 0xbd, 0x9e, 0x3e, 0xda, 0xed,
	0x5d, 0xc1, 0xd9, 0x30, 0xce, 0xff, 0xc6, 0xef, 0x0b, 0xfc, 0xb7, 0xf4, 0x2b, 0xb2, 0x3a, 0xfd,
	0x4a, 0x93, 0xdb, 0x47, 0x53, 0x59, 0xa5, 0xc7, 0x53, 0xe9, 0x09, 0x38, 0xa0, 0xc1, 0x7c, 0x3e,
	0x8d, 0xc7, 0xf4, 0xbe, 0x49, 0x6c, 0x25, 0xda, 0x83, 0x8e, 0x7c, 0x1c, 0xa3, 0xa1, 0xc4, 0x2e,
	0x05, 0xc6, 0x52, 0x29, 0xb4, 0x37, 0x75, 0xda, 0x0f, 0x94, 0x5b, 0x6d, 0x0f, 0xfd, 0x67, 0x03,
	0x9e, 0x56, 0xcc, 0xce, 0xb3, 0xf4, 0x26, 0x9e, 0x5a, 0x9f, 0xd1, 0x01, 0x6c, 0x56, 0x8c, 0x57,
	0x71, 0xaa, 0x42, 0x35, 0x13, 0xcf, 0x96, 0x49, 0xd3, 0x96, 0x89, 0xde, 0xae, 0x08, 0xc3, 0xba,
	0x7c, 0x03, 0xe2, 0x71, 0xb5, 0x49, 0x71, 0x44, 0xaf, 0x61, 0xbb, 0x60, 0xf9, 0x7d, 0x9c, 0xdc,
	0xb2, 0x6c, 0x9e, 0xc5, 0x09, 0xc7, 0xeb, 0xbe, 0x1b, 0x6e, 0x10, 0x93, 0x0a, 0x05, 0xb0, 0x51,
	0x88, 0x2f, 0xe8, 0x94, 0xe3, 0xb6, 0x30, 0x55, 0x64, 0xc1, 0x4b, 0x13, 0x25, 0x36, 0x02, 0x7f,
	0xb4, 0x61, 0x4b, 0x1b, 0x83, 0xe8, 0x48, 0x6b, 0x47, 0x41, 0x53, 0xb7, 0x8f, 0xc4, 0xcc, 0x54,
	0x34, 0x91, 0x43, 0xb4, 0xce, 0x3d, 0xd2, 0xba, 0x45, 0x10, 0xa8, 0xfa, 0x4a, 0x4d, 0xe9, 0x5b,
	0xc4, 0x76, 0xa4, 0xb5, 0x8c, 0xe0, 0x58, 0xf5, 0x95, 0x9a, 0xd2, 0xb7, 0xa0, 0xf2, 0x58, 0xef,
	0x1b, 0x51, 0x87, 0x6e, 0x7f, 0xbb, 0x7a, 0xb1, 0x54, 0x45, 0x0e, 0xd1, 0x9b, 0x8c, 0x58, 0xda,
	0x47, 0x54, 0xac, 0xdb, 0xdf, 0xad, 0xa0, 0x68, 0x16, 0x91, 0x43, 0x2c, 0x9d, 0x77, 0xac, 0x2f,
	0x11, 0x51, 0xd8, 0x22, 0x24, 0x55, 0x75, 0x1f, 0x92, 0xb6, 0x71, 0x8e, 0xf5, 0x29, 0x2f, 0x8a,
	0xad, 0xb9, 0x97, 0x5c, 0xea, 0x2b, 0x81, 0xd6, 0xad, 0x00, 0xdc, 0x11, 0x50, 0xcf, 0x54, 0xa8,
	0x07, 0x66, 0x91, 0x43, 0xea, 0xf6, 0xc8, 0x6d, 0xfd, 0x3e, 0xc0, 0x20, 0x2e, 0x79, 0x6e, 0xbf,
	0x44, 0x1a, 0x46, 0x0e, 0xa9, 0x5f, 0x2c, 0x23, 0xd3, 0x04, 0xc2, 0x5d, 0x01, 0xff, 0x64, 0x09,
	0xff, 0x40, 0x1d, 0x39, 0xc4, 0x34, 0xb6, 0x46, 0xa6, 0xb1, 0x82, 0x37, 0xcc, 0x50, 0x25, 0xbb,
	0xa6, 0x59, 0x74, 0x55, 0x33, 0x7a, 0xf0, 0xa6, 0x40, 0xdc, 0xd7, 0x11, 0x55, 0xab, 0xc8, 0x21,
	0x35, 0xd3, 0xeb, 0xaa, 0xa6, 0x8f, 0x71, 0xaf, 0x16, 0xbf, 0x0c, 0xdc, 0x0e, 0x71, 0xb2, 0x0e,
	0x6b, 0x67, 0xf7, 0xff, 0x3b, 0xd7, 0x2d, 0xf1, 0xfb, 0xf4, 0xe6, 0x4f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x16, 0x7f, 0xae, 0x57, 0x4d, 0x09, 0x00, 0x00,
}
