// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

package fsm

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StateTransitionSet struct {
	Events               []*StateTransition `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *StateTransitionSet) Reset()         { *m = StateTransitionSet{} }
func (m *StateTransitionSet) String() string { return proto.CompactTextString(m) }
func (*StateTransitionSet) ProtoMessage()    {}
func (*StateTransitionSet) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{0}
}

func (m *StateTransitionSet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransitionSet.Unmarshal(m, b)
}
func (m *StateTransitionSet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransitionSet.Marshal(b, m, deterministic)
}
func (m *StateTransitionSet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransitionSet.Merge(m, src)
}
func (m *StateTransitionSet) XXX_Size() int {
	return xxx_messageInfo_StateTransitionSet.Size(m)
}
func (m *StateTransitionSet) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransitionSet.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransitionSet proto.InternalMessageInfo

func (m *StateTransitionSet) GetEvents() []*StateTransition {
	if m != nil {
		return m.Events
	}
	return nil
}

type PeerLost struct {
	Peer                 uint64   `protobuf:"varint,1,opt,name=Peer,proto3" json:"Peer,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PeerLost) Reset()         { *m = PeerLost{} }
func (m *PeerLost) String() string { return proto.CompactTextString(m) }
func (*PeerLost) ProtoMessage()    {}
func (*PeerLost) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{1}
}

func (m *PeerLost) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PeerLost.Unmarshal(m, b)
}
func (m *PeerLost) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PeerLost.Marshal(b, m, deterministic)
}
func (m *PeerLost) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PeerLost.Merge(m, src)
}
func (m *PeerLost) XXX_Size() int {
	return xxx_messageInfo_PeerLost.Size(m)
}
func (m *PeerLost) XXX_DiscardUnknown() {
	xxx_messageInfo_PeerLost.DiscardUnknown(m)
}

var xxx_messageInfo_PeerLost proto.InternalMessageInfo

func (m *PeerLost) GetPeer() uint64 {
	if m != nil {
		return m.Peer
	}
	return 0
}

type AccountCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Principals           []string `protobuf:"bytes,3,rep,name=Principals,proto3" json:"Principals,omitempty"`
	DeviceUsernames      []string `protobuf:"bytes,4,rep,name=DeviceUsernames,proto3" json:"DeviceUsernames,omitempty"`
	CreatedAt            int64    `protobuf:"varint,5,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountCreated) Reset()         { *m = AccountCreated{} }
func (m *AccountCreated) String() string { return proto.CompactTextString(m) }
func (*AccountCreated) ProtoMessage()    {}
func (*AccountCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{2}
}

func (m *AccountCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountCreated.Unmarshal(m, b)
}
func (m *AccountCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountCreated.Marshal(b, m, deterministic)
}
func (m *AccountCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountCreated.Merge(m, src)
}
func (m *AccountCreated) XXX_Size() int {
	return xxx_messageInfo_AccountCreated.Size(m)
}
func (m *AccountCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountCreated.DiscardUnknown(m)
}

var xxx_messageInfo_AccountCreated proto.InternalMessageInfo

func (m *AccountCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AccountCreated) GetPrincipals() []string {
	if m != nil {
		return m.Principals
	}
	return nil
}

func (m *AccountCreated) GetDeviceUsernames() []string {
	if m != nil {
		return m.DeviceUsernames
	}
	return nil
}

func (m *AccountCreated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type AccountDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeleted) Reset()         { *m = AccountDeleted{} }
func (m *AccountDeleted) String() string { return proto.CompactTextString(m) }
func (*AccountDeleted) ProtoMessage()    {}
func (*AccountDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{3}
}

func (m *AccountDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeleted.Unmarshal(m, b)
}
func (m *AccountDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeleted.Marshal(b, m, deterministic)
}
func (m *AccountDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeleted.Merge(m, src)
}
func (m *AccountDeleted) XXX_Size() int {
	return xxx_messageInfo_AccountDeleted.Size(m)
}
func (m *AccountDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeleted proto.InternalMessageInfo

func (m *AccountDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

type AccountDeviceUsernameAdded struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceUsername       string   `protobuf:"bytes,2,opt,name=DeviceUsername,proto3" json:"DeviceUsername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeviceUsernameAdded) Reset()         { *m = AccountDeviceUsernameAdded{} }
func (m *AccountDeviceUsernameAdded) String() string { return proto.CompactTextString(m) }
func (*AccountDeviceUsernameAdded) ProtoMessage()    {}
func (*AccountDeviceUsernameAdded) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{4}
}

func (m *AccountDeviceUsernameAdded) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeviceUsernameAdded.Unmarshal(m, b)
}
func (m *AccountDeviceUsernameAdded) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeviceUsernameAdded.Marshal(b, m, deterministic)
}
func (m *AccountDeviceUsernameAdded) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeviceUsernameAdded.Merge(m, src)
}
func (m *AccountDeviceUsernameAdded) XXX_Size() int {
	return xxx_messageInfo_AccountDeviceUsernameAdded.Size(m)
}
func (m *AccountDeviceUsernameAdded) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeviceUsernameAdded.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeviceUsernameAdded proto.InternalMessageInfo

func (m *AccountDeviceUsernameAdded) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountDeviceUsernameAdded) GetDeviceUsername() string {
	if m != nil {
		return m.DeviceUsername
	}
	return ""
}

type AccountDeviceUsernameRemoved struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	DeviceUsername       string   `protobuf:"bytes,2,opt,name=DeviceUsername,proto3" json:"DeviceUsername,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AccountDeviceUsernameRemoved) Reset()         { *m = AccountDeviceUsernameRemoved{} }
func (m *AccountDeviceUsernameRemoved) String() string { return proto.CompactTextString(m) }
func (*AccountDeviceUsernameRemoved) ProtoMessage()    {}
func (*AccountDeviceUsernameRemoved) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{5}
}

func (m *AccountDeviceUsernameRemoved) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AccountDeviceUsernameRemoved.Unmarshal(m, b)
}
func (m *AccountDeviceUsernameRemoved) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AccountDeviceUsernameRemoved.Marshal(b, m, deterministic)
}
func (m *AccountDeviceUsernameRemoved) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AccountDeviceUsernameRemoved.Merge(m, src)
}
func (m *AccountDeviceUsernameRemoved) XXX_Size() int {
	return xxx_messageInfo_AccountDeviceUsernameRemoved.Size(m)
}
func (m *AccountDeviceUsernameRemoved) XXX_DiscardUnknown() {
	xxx_messageInfo_AccountDeviceUsernameRemoved.DiscardUnknown(m)
}

var xxx_messageInfo_AccountDeviceUsernameRemoved proto.InternalMessageInfo

func (m *AccountDeviceUsernameRemoved) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *AccountDeviceUsernameRemoved) GetDeviceUsername() string {
	if m != nil {
		return m.DeviceUsername
	}
	return ""
}

type DeviceCreated struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	Active               bool     `protobuf:"varint,4,opt,name=Active,proto3" json:"Active,omitempty"`
	Password             string   `protobuf:"bytes,5,opt,name=Password,proto3" json:"Password,omitempty"`
	CreatedAt            int64    `protobuf:"varint,6,opt,name=CreatedAt,proto3" json:"CreatedAt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceCreated) Reset()         { *m = DeviceCreated{} }
func (m *DeviceCreated) String() string { return proto.CompactTextString(m) }
func (*DeviceCreated) ProtoMessage()    {}
func (*DeviceCreated) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{6}
}

func (m *DeviceCreated) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceCreated.Unmarshal(m, b)
}
func (m *DeviceCreated) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceCreated.Marshal(b, m, deterministic)
}
func (m *DeviceCreated) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceCreated.Merge(m, src)
}
func (m *DeviceCreated) XXX_Size() int {
	return xxx_messageInfo_DeviceCreated.Size(m)
}
func (m *DeviceCreated) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceCreated.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceCreated proto.InternalMessageInfo

func (m *DeviceCreated) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceCreated) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DeviceCreated) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *DeviceCreated) GetActive() bool {
	if m != nil {
		return m.Active
	}
	return false
}

func (m *DeviceCreated) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *DeviceCreated) GetCreatedAt() int64 {
	if m != nil {
		return m.CreatedAt
	}
	return 0
}

type DeviceDeleted struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDeleted) Reset()         { *m = DeviceDeleted{} }
func (m *DeviceDeleted) String() string { return proto.CompactTextString(m) }
func (*DeviceDeleted) ProtoMessage()    {}
func (*DeviceDeleted) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{7}
}

func (m *DeviceDeleted) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDeleted.Unmarshal(m, b)
}
func (m *DeviceDeleted) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDeleted.Marshal(b, m, deterministic)
}
func (m *DeviceDeleted) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDeleted.Merge(m, src)
}
func (m *DeviceDeleted) XXX_Size() int {
	return xxx_messageInfo_DeviceDeleted.Size(m)
}
func (m *DeviceDeleted) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDeleted.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDeleted proto.InternalMessageInfo

func (m *DeviceDeleted) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceDeleted) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeviceEnabled struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceEnabled) Reset()         { *m = DeviceEnabled{} }
func (m *DeviceEnabled) String() string { return proto.CompactTextString(m) }
func (*DeviceEnabled) ProtoMessage()    {}
func (*DeviceEnabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{8}
}

func (m *DeviceEnabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceEnabled.Unmarshal(m, b)
}
func (m *DeviceEnabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceEnabled.Marshal(b, m, deterministic)
}
func (m *DeviceEnabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceEnabled.Merge(m, src)
}
func (m *DeviceEnabled) XXX_Size() int {
	return xxx_messageInfo_DeviceEnabled.Size(m)
}
func (m *DeviceEnabled) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceEnabled.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceEnabled proto.InternalMessageInfo

func (m *DeviceEnabled) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceEnabled) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DeviceDisabled struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DeviceDisabled) Reset()         { *m = DeviceDisabled{} }
func (m *DeviceDisabled) String() string { return proto.CompactTextString(m) }
func (*DeviceDisabled) ProtoMessage()    {}
func (*DeviceDisabled) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{9}
}

func (m *DeviceDisabled) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DeviceDisabled.Unmarshal(m, b)
}
func (m *DeviceDisabled) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DeviceDisabled.Marshal(b, m, deterministic)
}
func (m *DeviceDisabled) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DeviceDisabled.Merge(m, src)
}
func (m *DeviceDisabled) XXX_Size() int {
	return xxx_messageInfo_DeviceDisabled.Size(m)
}
func (m *DeviceDisabled) XXX_DiscardUnknown() {
	xxx_messageInfo_DeviceDisabled.DiscardUnknown(m)
}

var xxx_messageInfo_DeviceDisabled proto.InternalMessageInfo

func (m *DeviceDisabled) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DeviceDisabled) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type DevicePasswordChanged struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	Owner                string   `protobuf:"bytes,2,opt,name=Owner,proto3" json:"Owner,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=Password,proto3" json:"Password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DevicePasswordChanged) Reset()         { *m = DevicePasswordChanged{} }
func (m *DevicePasswordChanged) String() string { return proto.CompactTextString(m) }
func (*DevicePasswordChanged) ProtoMessage()    {}
func (*DevicePasswordChanged) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{10}
}

func (m *DevicePasswordChanged) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DevicePasswordChanged.Unmarshal(m, b)
}
func (m *DevicePasswordChanged) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DevicePasswordChanged.Marshal(b, m, deterministic)
}
func (m *DevicePasswordChanged) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DevicePasswordChanged.Merge(m, src)
}
func (m *DevicePasswordChanged) XXX_Size() int {
	return xxx_messageInfo_DevicePasswordChanged.Size(m)
}
func (m *DevicePasswordChanged) XXX_DiscardUnknown() {
	xxx_messageInfo_DevicePasswordChanged.DiscardUnknown(m)
}

var xxx_messageInfo_DevicePasswordChanged proto.InternalMessageInfo

func (m *DevicePasswordChanged) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *DevicePasswordChanged) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *DevicePasswordChanged) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type StateTransition struct {
	// Types that are valid to be assigned to Event:
	//	*StateTransition_PeerLost
	//	*StateTransition_DeviceCreated
	//	*StateTransition_DeviceDeleted
	//	*StateTransition_DeviceEnabled
	//	*StateTransition_DeviceDisabled
	//	*StateTransition_DevicePasswordChanged
	//	*StateTransition_AccountCreated
	//	*StateTransition_AccountDeleted
	//	*StateTransition_AccountDeviceUsernameAdded
	//	*StateTransition_AccountDeviceUsernameRemoved
	Event                isStateTransition_Event `protobuf_oneof:"Event"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *StateTransition) Reset()         { *m = StateTransition{} }
func (m *StateTransition) String() string { return proto.CompactTextString(m) }
func (*StateTransition) ProtoMessage()    {}
func (*StateTransition) Descriptor() ([]byte, []int) {
	return fileDescriptor_d938547f84707355, []int{11}
}

func (m *StateTransition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StateTransition.Unmarshal(m, b)
}
func (m *StateTransition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StateTransition.Marshal(b, m, deterministic)
}
func (m *StateTransition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StateTransition.Merge(m, src)
}
func (m *StateTransition) XXX_Size() int {
	return xxx_messageInfo_StateTransition.Size(m)
}
func (m *StateTransition) XXX_DiscardUnknown() {
	xxx_messageInfo_StateTransition.DiscardUnknown(m)
}

var xxx_messageInfo_StateTransition proto.InternalMessageInfo

type isStateTransition_Event interface {
	isStateTransition_Event()
}

type StateTransition_PeerLost struct {
	PeerLost *PeerLost `protobuf:"bytes,1,opt,name=PeerLost,proto3,oneof"`
}

type StateTransition_DeviceCreated struct {
	DeviceCreated *DeviceCreated `protobuf:"bytes,2,opt,name=DeviceCreated,proto3,oneof"`
}

type StateTransition_DeviceDeleted struct {
	DeviceDeleted *DeviceDeleted `protobuf:"bytes,3,opt,name=DeviceDeleted,proto3,oneof"`
}

type StateTransition_DeviceEnabled struct {
	DeviceEnabled *DeviceEnabled `protobuf:"bytes,4,opt,name=DeviceEnabled,proto3,oneof"`
}

type StateTransition_DeviceDisabled struct {
	DeviceDisabled *DeviceDisabled `protobuf:"bytes,5,opt,name=DeviceDisabled,proto3,oneof"`
}

type StateTransition_DevicePasswordChanged struct {
	DevicePasswordChanged *DevicePasswordChanged `protobuf:"bytes,6,opt,name=DevicePasswordChanged,proto3,oneof"`
}

type StateTransition_AccountCreated struct {
	AccountCreated *AccountCreated `protobuf:"bytes,7,opt,name=AccountCreated,proto3,oneof"`
}

type StateTransition_AccountDeleted struct {
	AccountDeleted *AccountDeleted `protobuf:"bytes,8,opt,name=AccountDeleted,proto3,oneof"`
}

type StateTransition_AccountDeviceUsernameAdded struct {
	AccountDeviceUsernameAdded *AccountDeviceUsernameAdded `protobuf:"bytes,9,opt,name=AccountDeviceUsernameAdded,proto3,oneof"`
}

type StateTransition_AccountDeviceUsernameRemoved struct {
	AccountDeviceUsernameRemoved *AccountDeviceUsernameRemoved `protobuf:"bytes,10,opt,name=AccountDeviceUsernameRemoved,proto3,oneof"`
}

func (*StateTransition_PeerLost) isStateTransition_Event() {}

func (*StateTransition_DeviceCreated) isStateTransition_Event() {}

func (*StateTransition_DeviceDeleted) isStateTransition_Event() {}

func (*StateTransition_DeviceEnabled) isStateTransition_Event() {}

func (*StateTransition_DeviceDisabled) isStateTransition_Event() {}

func (*StateTransition_DevicePasswordChanged) isStateTransition_Event() {}

func (*StateTransition_AccountCreated) isStateTransition_Event() {}

func (*StateTransition_AccountDeleted) isStateTransition_Event() {}

func (*StateTransition_AccountDeviceUsernameAdded) isStateTransition_Event() {}

func (*StateTransition_AccountDeviceUsernameRemoved) isStateTransition_Event() {}

func (m *StateTransition) GetEvent() isStateTransition_Event {
	if m != nil {
		return m.Event
	}
	return nil
}

func (m *StateTransition) GetPeerLost() *PeerLost {
	if x, ok := m.GetEvent().(*StateTransition_PeerLost); ok {
		return x.PeerLost
	}
	return nil
}

func (m *StateTransition) GetDeviceCreated() *DeviceCreated {
	if x, ok := m.GetEvent().(*StateTransition_DeviceCreated); ok {
		return x.DeviceCreated
	}
	return nil
}

func (m *StateTransition) GetDeviceDeleted() *DeviceDeleted {
	if x, ok := m.GetEvent().(*StateTransition_DeviceDeleted); ok {
		return x.DeviceDeleted
	}
	return nil
}

func (m *StateTransition) GetDeviceEnabled() *DeviceEnabled {
	if x, ok := m.GetEvent().(*StateTransition_DeviceEnabled); ok {
		return x.DeviceEnabled
	}
	return nil
}

func (m *StateTransition) GetDeviceDisabled() *DeviceDisabled {
	if x, ok := m.GetEvent().(*StateTransition_DeviceDisabled); ok {
		return x.DeviceDisabled
	}
	return nil
}

func (m *StateTransition) GetDevicePasswordChanged() *DevicePasswordChanged {
	if x, ok := m.GetEvent().(*StateTransition_DevicePasswordChanged); ok {
		return x.DevicePasswordChanged
	}
	return nil
}

func (m *StateTransition) GetAccountCreated() *AccountCreated {
	if x, ok := m.GetEvent().(*StateTransition_AccountCreated); ok {
		return x.AccountCreated
	}
	return nil
}

func (m *StateTransition) GetAccountDeleted() *AccountDeleted {
	if x, ok := m.GetEvent().(*StateTransition_AccountDeleted); ok {
		return x.AccountDeleted
	}
	return nil
}

func (m *StateTransition) GetAccountDeviceUsernameAdded() *AccountDeviceUsernameAdded {
	if x, ok := m.GetEvent().(*StateTransition_AccountDeviceUsernameAdded); ok {
		return x.AccountDeviceUsernameAdded
	}
	return nil
}

func (m *StateTransition) GetAccountDeviceUsernameRemoved() *AccountDeviceUsernameRemoved {
	if x, ok := m.GetEvent().(*StateTransition_AccountDeviceUsernameRemoved); ok {
		return x.AccountDeviceUsernameRemoved
	}
	return nil
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*StateTransition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*StateTransition_PeerLost)(nil),
		(*StateTransition_DeviceCreated)(nil),
		(*StateTransition_DeviceDeleted)(nil),
		(*StateTransition_DeviceEnabled)(nil),
		(*StateTransition_DeviceDisabled)(nil),
		(*StateTransition_DevicePasswordChanged)(nil),
		(*StateTransition_AccountCreated)(nil),
		(*StateTransition_AccountDeleted)(nil),
		(*StateTransition_AccountDeviceUsernameAdded)(nil),
		(*StateTransition_AccountDeviceUsernameRemoved)(nil),
	}
}

func init() {
	proto.RegisterType((*StateTransitionSet)(nil), "fsm.StateTransitionSet")
	proto.RegisterType((*PeerLost)(nil), "fsm.PeerLost")
	proto.RegisterType((*AccountCreated)(nil), "fsm.AccountCreated")
	proto.RegisterType((*AccountDeleted)(nil), "fsm.AccountDeleted")
	proto.RegisterType((*AccountDeviceUsernameAdded)(nil), "fsm.AccountDeviceUsernameAdded")
	proto.RegisterType((*AccountDeviceUsernameRemoved)(nil), "fsm.AccountDeviceUsernameRemoved")
	proto.RegisterType((*DeviceCreated)(nil), "fsm.DeviceCreated")
	proto.RegisterType((*DeviceDeleted)(nil), "fsm.DeviceDeleted")
	proto.RegisterType((*DeviceEnabled)(nil), "fsm.DeviceEnabled")
	proto.RegisterType((*DeviceDisabled)(nil), "fsm.DeviceDisabled")
	proto.RegisterType((*DevicePasswordChanged)(nil), "fsm.DevicePasswordChanged")
	proto.RegisterType((*StateTransition)(nil), "fsm.StateTransition")
}

func init() { proto.RegisterFile("types.proto", fileDescriptor_d938547f84707355) }

var fileDescriptor_d938547f84707355 = []byte{
	// 549 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0x51, 0x6b, 0xdb, 0x30,
	0x10, 0xb6, 0xeb, 0x24, 0x4d, 0xce, 0x34, 0x05, 0xad, 0x1b, 0x22, 0x94, 0xce, 0xf3, 0xc3, 0x30,
	0x6c, 0xe4, 0x21, 0x63, 0x7b, 0x08, 0xe4, 0x21, 0xad, 0x0b, 0x2e, 0x8c, 0x2d, 0xa8, 0xdd, 0x60,
	0x8f, 0xaa, 0x73, 0xed, 0x0c, 0xb1, 0x1d, 0x2c, 0x2d, 0x65, 0xbf, 0x65, 0xfb, 0x61, 0xfb, 0x39,
	0x23, 0x8a, 0x1d, 0xdb, 0x6a, 0x1c, 0x3a, 0xf6, 0x26, 0xdd, 0xdd, 0x77, 0x77, 0xfa, 0x3e, 0xe9,
	0x04, 0xb6, 0xfc, 0xb9, 0x44, 0x31, 0x5c, 0x66, 0xa9, 0x4c, 0x89, 0x75, 0x27, 0x62, 0xf7, 0x1c,
	0xc8, 0xb5, 0xe4, 0x12, 0x6f, 0x32, 0x9e, 0x88, 0x48, 0x46, 0x69, 0x72, 0x8d, 0x92, 0xbc, 0x85,
	0x0e, 0xae, 0x30, 0x91, 0x82, 0x9a, 0x8e, 0xe5, 0xd9, 0xa3, 0x93, 0xe1, 0x9d, 0x88, 0x87, 0x5a,
	0x20, 0xcb, 0x63, 0xdc, 0x33, 0xe8, 0xce, 0x10, 0xb3, 0x8f, 0xa9, 0x90, 0x84, 0x40, 0x6b, 0xbd,
	0xa6, 0xa6, 0x63, 0x7a, 0x2d, 0xa6, 0xd6, 0xee, 0x6f, 0x13, 0xfa, 0xd3, 0x30, 0x4c, 0x7f, 0x24,
	0xf2, 0x22, 0x43, 0x2e, 0x71, 0x4e, 0xfa, 0x70, 0x70, 0xe5, 0xab, 0xa0, 0x1e, 0x3b, 0xb8, 0xf2,
	0xd7, 0xb0, 0x4f, 0x3c, 0x46, 0x7a, 0xa0, 0x2c, 0x6a, 0x4d, 0xce, 0x00, 0x66, 0x59, 0x94, 0x84,
	0xd1, 0x92, 0x2f, 0x04, 0xb5, 0x1c, 0xcb, 0xeb, 0xb1, 0x8a, 0x85, 0x78, 0x70, 0xec, 0xe3, 0x2a,
	0x0a, 0xf1, 0x8b, 0xc0, 0x2c, 0xe1, 0x31, 0x0a, 0xda, 0x52, 0x41, 0xba, 0x99, 0x9c, 0x42, 0x2f,
	0x2f, 0x3c, 0x95, 0xb4, 0xed, 0x98, 0x9e, 0xc5, 0x4a, 0x83, 0xeb, 0x6c, 0xbb, 0xf3, 0x71, 0x81,
	0x3b, 0xba, 0x73, 0x6f, 0x60, 0xb0, 0x8d, 0xa8, 0x66, 0x9e, 0xce, 0xe7, 0x3b, 0xce, 0xf2, 0x1a,
	0xfa, 0xf5, 0xb0, 0xfc, 0x54, 0x9a, 0xd5, 0xfd, 0x0a, 0xa7, 0x3b, 0xb3, 0x32, 0x8c, 0xd3, 0xd5,
	0x7f, 0xe4, 0xfd, 0x65, 0xc2, 0xd1, 0xc6, 0xd4, 0xc4, 0xf6, 0x09, 0xb4, 0x3f, 0x3f, 0x24, 0x98,
	0xe5, 0x09, 0x36, 0x9b, 0xad, 0x06, 0x56, 0x45, 0x83, 0x17, 0xd0, 0x99, 0x86, 0x32, 0x5a, 0x21,
	0x6d, 0x39, 0xa6, 0xd7, 0x65, 0xf9, 0x8e, 0x0c, 0xa0, 0x3b, 0xe3, 0x42, 0x3c, 0xa4, 0xd9, 0x5c,
	0x11, 0xda, 0x63, 0xdb, 0x7d, 0x9d, 0xed, 0x8e, 0xce, 0xf6, 0xfb, 0xa2, 0xb9, 0x06, 0xb2, 0x77,
	0x37, 0x57, 0xc2, 0x2e, 0x13, 0x7e, 0xbb, 0x78, 0x32, 0xec, 0x43, 0xc1, 0x99, 0x1f, 0x89, 0x7f,
	0xc1, 0x7d, 0x83, 0xe7, 0x1b, 0x5c, 0x71, 0xaa, 0x8b, 0xef, 0x3c, 0xb9, 0x7f, 0x32, 0x95, 0x55,
	0x7a, 0xac, 0x3a, 0x3d, 0xee, 0x9f, 0x36, 0x1c, 0x6b, 0x2f, 0x89, 0xbc, 0x29, 0x5f, 0x90, 0xca,
	0x6d, 0x8f, 0x8e, 0xd4, 0x8b, 0x2b, 0x8c, 0x81, 0xc1, 0xca, 0x27, 0x36, 0xd6, 0xe4, 0x55, 0xa5,
	0xed, 0x11, 0x51, 0x88, 0x9a, 0x27, 0x30, 0x98, 0x76, 0x13, 0xc6, 0x1a, 0xfb, 0xaa, 0xbb, 0x3a,
	0x36, 0xf7, 0x94, 0xd8, 0x42, 0xa8, 0xb1, 0x26, 0x81, 0xba, 0x12, 0x75, 0x6c, 0xee, 0x29, 0xb1,
	0x85, 0x5a, 0x13, 0x5d, 0x07, 0x75, 0x6b, 0xec, 0xd1, 0xb3, 0x6a, 0xe1, 0xdc, 0x15, 0x18, 0x4c,
	0x17, 0x8d, 0x35, 0xc8, 0xa1, 0xae, 0x97, 0x3d, 0x1a, 0x54, 0xb2, 0x68, 0x11, 0x81, 0xc1, 0x1a,
	0x94, 0x9c, 0xe8, 0x43, 0x89, 0x1e, 0x56, 0x5a, 0xaa, 0xbb, 0xd6, 0x2d, 0x69, 0x13, 0x6c, 0xa2,
	0x4f, 0x0d, 0xda, 0x7d, 0x0c, 0x2f, 0xb9, 0xd4, 0x47, 0x0c, 0xdf, 0x37, 0x52, 0x68, 0x4f, 0xa5,
	0x7a, 0x59, 0x4f, 0xf5, 0x28, 0x2c, 0x30, 0xd8, 0xbe, 0xb9, 0x74, 0xbf, 0x7f, 0xbe, 0x50, 0x50,
	0x45, 0x5e, 0x35, 0x17, 0xc9, 0x03, 0x03, 0x83, 0xed, 0x4d, 0x74, 0x7e, 0x08, 0xed, 0xcb, 0xf5,
	0x4f, 0x70, 0xdb, 0x51, 0x1f, 0xcb, 0xbb, 0xbf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xa4, 0xfa, 0xe5,
	0x3e, 0x67, 0x06, 0x00, 0x00,
}
